### PR TITLE
Update 'Motivations' in README

### PR DESCRIPTION
**Pull request by saneyuki**
This change is [Reviewable](https://reviewable.io/reviews/karen-irc/popuko/172)

### CODE REVIEW

**Comment by nekoya** [comment]
@popuko r+

**Comment by popuko** [comment]
:pushpin: Commit d23ef0467b48ac721eda6261077cdccac51a9411 has been approved by `nekoya`

**Comment by popuko** [comment]
:hourglass: d23ef0467b48ac721eda6261077cdccac51a9411 has been merged into the auto branch 341140ab84954cdfe576fdfe1671d4bab0c51df2

**Comment by popuko** [comment]
:tada: The branch status which tried to merge this pull request into master is: success

* [The Travis CI build passed](https://travis-ci.org/karen-irc/popuko/builds/190472076)

**Pull request merged**
