### PR TITLE
Use the implementation of golang's http.Dir for queue.createAbs()

### PR DESCRIPTION
**Pull request by saneyuki**
Fix https://github.com/karen-irc/popuko/issues/216

---
This change is [Reviewable](https://reviewable.io/reviews/karen-irc/popuko/221)

### CODE REVIEW

**Comment by nekoya** [comment]
Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/karen-irc/popuko/221)*

**Comment by nekoya** [comment]
@popuko r+

**Comment by popuko** [comment]
:pushpin: Commit 65108ecf84f91e8f8462c40d30baeb5943dd0cab has been approved by `nekoya`

**Comment by popuko** [comment]
:hourglass: 65108ecf84f91e8f8462c40d30baeb5943dd0cab has been merged into the auto branch fce999f8825dfa69c0e17e38b5c3a5e87cae599a

**Comment by popuko** [comment]
:tada: The result of what tried to merge this pull request is `success`.

* [The Travis CI build passed](https://travis-ci.org/karen-irc/popuko/builds/195742742)

**Pull request merged**
