### PR TITLE
Make Auto-Branch name configurable

### PR DESCRIPTION
**Pull request by saneyuki**
Fix https://github.com/karen-irc/popuko/issues/99

---
This change is [Reviewable](https://reviewable.io/reviews/karen-irc/popuko/181)

### CODE REVIEW

**Comment by nekoya** [comment]
Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/karen-irc/popuko/181)*

**Comment by nekoya** [comment]
@popuko r+

**Comment by popuko** [comment]
:pushpin: Commit 28ed78ca6cf1519124364a26c42fb4beca3353ff has been approved by `nekoya`

**Comment by popuko** [comment]
:hourglass: 28ed78ca6cf1519124364a26c42fb4beca3353ff has been merged into the auto branch d269f58e5aab29692f16ec6725b8119153ef3c01

**Comment by popuko** [comment]
:tada: The result of what tried to merge this pull request is `success`.

* [The Travis CI build passed](https://travis-ci.org/karen-irc/popuko/builds/190555491)

**Pull request merged**
