### PR TITLE
Change the links to the current one.

### PR DESCRIPTION
**Pull request by saneyuki**

### CODE REVIEW

**Comment by saneyuki** [comment]
@popuko r+

**Comment by popuko** [comment]
:pushpin: Commit 081c04ed305d537cdb220e420cb89d633d7494dd has been approved by `saneyuki`

**Comment by popuko** [comment]
:hourglass: 081c04ed305d537cdb220e420cb89d633d7494dd has been merged into the auto branch https://github.com/karen-irc/popuko/commit/fccef50b30e4ce111a334a85e98215c57ddcea37

**Comment by popuko** [comment]
:tada: success: The branch testing to merge this pull request into master has been succeed.

* [The Travis CI build passed](https://travis-ci.org/karen-irc/popuko/builds/185684078)

**Comment by popuko** [comment]
:hourglass: Try to merge 081c04ed305d537cdb220e420cb89d633d7494dd into `master`

**Pull request merged**
