### PR TITLE
Add more descriptions to 'How to Contribute'.

### PR DESCRIPTION
**Pull request by saneyuki**
This change is [Reviewable](https://reviewable.io/reviews/karen-irc/popuko/190)

### CODE REVIEW

**Comment by saneyuki** [comment]
@popuko r+

**Comment by popuko** [comment]
:pushpin: Commit 8c5ef2604387818e1937195809e8f8a0ca5acf67 has been approved by `saneyuki`

**Comment by popuko** [comment]
:hourglass: 8c5ef2604387818e1937195809e8f8a0ca5acf67 has been merged into the auto branch 5e9956dc22eca86a703fc80ed76fac60d9c81071

**Comment by popuko** [comment]
:tada: The result of what tried to merge this pull request is `success`.

* [The Travis CI build passed](https://travis-ci.org/karen-irc/popuko/builds/191209737)

**Pull request merged**
