### PR TITLE
Specify the config dir via -config-base-dir directly.

### PR DESCRIPTION
**Pull request by saneyuki**
This change is [Reviewable](https://reviewable.io/reviews/karen-irc/popuko/164)

### CODE REVIEW

**Comment by saneyuki** [comment]
@popuko r+

**Comment by popuko** [comment]
:pushpin: Commit fbb3424fe0891613a0f1ff8cd1ed7b53dd12c619 has been approved by `saneyuki`

**Comment by popuko** [comment]
:hourglass: fbb3424fe0891613a0f1ff8cd1ed7b53dd12c619 has been merged into the auto branch 0d10ba6684352b820b2fefafd0df6999e97f3d9c

**Comment by popuko** [comment]
:tada: success: The branch testing to merge this pull request into master has been succeed.

* [The Travis CI build passed](https://travis-ci.org/karen-irc/popuko/builds/189435051)

**Pull request merged**
