### PR TITLE
Add more parser testcases

### PR DESCRIPTION
**Pull request by saneyuki**
This change is [Reviewable](https://reviewable.io/reviews/karen-irc/popuko/199)

### CODE REVIEW

**Comment by saneyuki** [comment]
@popuko r+

**Comment by popuko** [comment]
:pushpin: Commit 0b09c4a3e570c7912fc132734da21d9f87dea517 has been approved by `saneyuki`

**Comment by popuko** [comment]
:hourglass: 0b09c4a3e570c7912fc132734da21d9f87dea517 has been merged into the auto branch 174ff06ed2767c910259ffda090c6393b559f1fe

**Comment by saneyuki** [comment]
@popuko r-

**Comment by popuko** [comment]
:outbox_tray: This has been cancelled from the approved queue by `saneyuki`

**Comment by saneyuki** [comment]
@popuko r+

**Comment by popuko** [comment]
:pushpin: Commit f0415dc834d25a5b2c7280e6333adcfef59d66b6 has been approved by `saneyuki`

**Comment by popuko** [comment]
:hourglass: f0415dc834d25a5b2c7280e6333adcfef59d66b6 has been merged into the auto branch 48bccd8e94fe69006d39323bed65d444337ae549

**Comment by saneyuki** [comment]
@popuko r-

**Comment by popuko** [comment]
:outbox_tray: This has been cancelled from the approved queue by `saneyuki`

**Comment by saneyuki** [comment]
@popuko r+

**Comment by popuko** [comment]
:pushpin: Commit 625b3222b9d4eefaa5dbd4cb42ad7ba1ead0f2b5 has been approved by `saneyuki`

**Comment by popuko** [comment]
:hourglass: 625b3222b9d4eefaa5dbd4cb42ad7ba1ead0f2b5 has been merged into the auto branch 098b7d937764a12dacbd2b0f0b27fc58947c7f08

**Comment by popuko** [comment]
:tada: The result of what tried to merge this pull request is `success`.

* [The Travis CI build passed](https://travis-ci.org/karen-irc/popuko/builds/191366588)

**Pull request merged**
