### PR TITLE
Use 'refs/pull/<PR_NUM>/merge' to create the auto branch

### PR DESCRIPTION
**Pull request by saneyuki**
- Fix https://github.com/karen-irc/popuko/issues/93
- Fix https://github.com/karen-irc/popuko/issues/140

---
This change is [Reviewable](https://reviewable.io/reviews/karen-irc/popuko/156)

### CODE REVIEW

**Comment by popuko** [comment]
:umbrella: The latest upstream change (presumably [these](https://github.com/karen-irc/popuko/compare/d25f51866001...d89787efbd20)) made this pull request unmergeable. Please resolve the merge conflicts.

**Comment by popuko** [comment]
:pushpin: Commit 7bba03e2969d8fd2b409565f3b873dc8d9c68d9e has been approved by `saneyuki`

**Comment by saneyuki** [comment]
@popuko r+

**Comment by popuko** [comment]
:pushpin: Commit 7bba03e2969d8fd2b409565f3b873dc8d9c68d9e has been approved by `saneyuki`

**Comment by popuko** [comment]
:hourglass: 7bba03e2969d8fd2b409565f3b873dc8d9c68d9e has been merged into the auto branch 5284f0fd33b331d0e24ef0b645bcffb87d3e6c0f

**Pull request merged**
