### PR TITLE
Use the latest golang/dep

### PR DESCRIPTION
**Pull request by saneyuki**
This change is [Reviewable](https://reviewable.io/reviews/karen-irc/popuko/230)

### CODE REVIEW

**Comment by nekoya** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[.gitignore, line 11 at r1](https://reviewable.io:443/reviews/karen-irc/popuko/230#-Khf0GXapZ3iLPi2DW4M:-Khf0GXapZ3iLPi2DW4N:b-86m1zb) ([raw file](https://github.com/karen-irc/popuko/blob/27f4eacf784df7c8e8f81f55f03d412bedd6e8e9/.gitignore#L11)):*
> ```
> 
> # https://github.com/golang/dep
> lock.json
> ```

We ignored `lock.json`, should we ignore `Gopkg.lock`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/karen-irc/popuko/230)*

**Comment by saneyuki** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[.gitignore, line 11 at r1](https://reviewable.io:443/reviews/karen-irc/popuko/230#-Khf0GXapZ3iLPi2DW4M:-Khf1ki_rv23xRXlEYUF:b-8rtt2r) ([raw file](https://github.com/karen-irc/popuko/blob/27f4eacf784df7c8e8f81f55f03d412bedd6e8e9/.gitignore#L11)):*
<details><summary><i>Previously, nekoya (Ryo Miyake) wrote…</i></summary><blockquote>

We ignored `lock.json`, should we ignore `Gopkg.lock`?
</blockquote></details>

@nekoya this is just an application. We should include lock file into the same repository. We were wrong decision about it and now we fix it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/karen-irc/popuko/230)*

**Comment by nekoya** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[.gitignore, line 11 at r1](https://reviewable.io:443/reviews/karen-irc/popuko/230#-Khf0GXapZ3iLPi2DW4M:-Khf2AB_sI_335amvhsr:bpgnszt) ([raw file](https://github.com/karen-irc/popuko/blob/27f4eacf784df7c8e8f81f55f03d412bedd6e8e9/.gitignore#L11)):*
<details><summary><i>Previously, saneyuki (Tetsuharu OHZEKI) wrote…</i></summary><blockquote>

@nekoya this is just an application. We should include lock file into the same repository. We were wrong decision about it and now we fix it.
</blockquote></details>

OK, I agree with it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/karen-irc/popuko/230)*

**Comment by nekoya** [comment]
@popuko r+

**Comment by popuko** [comment]
:pushpin: Commit 0e85ff95c3452db693e00ea8adf9aca3a8035014 has been approved by `nekoya`

**Comment by popuko** [comment]
:hourglass: 0e85ff95c3452db693e00ea8adf9aca3a8035014 has been merged into the auto branch 6fc04152eaf2a1d870dfacf0db0a1f847461cff5

**Comment by popuko** [comment]
:tada: The result of what tried to merge this pull request is `success`.

* [The Travis CI build passed](https://travis-ci.org/karen-irc/popuko/builds/221981723)

**Pull request merged**
