### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by saneyuki**
This change is [Reviewable](https://reviewable.io/reviews/karen-irc/popuko/170)

### CODE REVIEW

**Comment by saneyuki** [comment]
@popuko r+

**Comment by popuko** [comment]
:pushpin: Commit e8903645fb07433d47718e1771bcc9fa726edb47 has been approved by `saneyuki`

**Comment by popuko** [comment]
:hourglass: e8903645fb07433d47718e1771bcc9fa726edb47 has been merged into the auto branch fa0eaf56904b36baa138b64337e85d0b3857cbe6

**Comment by popuko** [comment]
:tada: The branch status which tried to merge this pull request into master is: success

* [The Travis CI build passed](https://travis-ci.org/karen-irc/popuko/builds/189546225)

**Pull request merged**
