### PR TITLE
Allow the failure building on go=master

### PR DESCRIPTION
**Pull request by saneyuki**
This change is [Reviewable](https://reviewable.io/reviews/karen-irc/popuko/232)

### CODE REVIEW

**Comment by saneyuki** [comment]
@popuko r+

**Comment by popuko** [comment]
:pushpin: Commit fb3fa4f66fd6a05eaa831eb9da21f8641bca4f86 has been approved by `saneyuki`

**Comment by popuko** [comment]
:hourglass: fb3fa4f66fd6a05eaa831eb9da21f8641bca4f86 has been merged into the auto branch 4c47369cc8f4d3fe8560513a7c1601ae243bc04c

**Comment by popuko** [comment]
:tada: The result of what tried to merge this pull request is `success`.

* [The Travis CI build passed](https://travis-ci.org/karen-irc/popuko/builds/221982397)

**Pull request merged**
