### PR TITLE
[demo] Write fot test

### PR DESCRIPTION
**Pull request by saneyuki**
Reverts karen-irc/popuko#125

### CODE REVIEW

**Comment by saneyuki** [comment]
@popuko r+

**Comment by popuko** [comment]
:pushpin: Commit 71214bf73844c2fcb79e8ea974f3464634fb2ceb has been approved by `saneyuki`

**Comment by popuko** [comment]
:postbox: This pull request is queued. Please await the time.

**Comment by saneyuki** [comment]
@popuko r+

**Comment by saneyuki** [comment]
@popuko r+

**Comment by popuko** [comment]
:pushpin: Commit 71214bf73844c2fcb79e8ea974f3464634fb2ceb has been approved by `saneyuki`

**Comment by popuko** [comment]
:hourglass: 71214bf73844c2fcb79e8ea974f3464634fb2ceb has been merged into the auto branch https://github.com/karen-irc/popuko/commit/0fa9629c380df1889d69326e8c9288c9b112af25

**Comment by saneyuki** [comment]
@popuko r+

**Comment by popuko** [comment]
:pushpin: Commit 71214bf73844c2fcb79e8ea974f3464634fb2ceb has been approved by `saneyuki`

**Comment by popuko** [comment]
:hourglass: 71214bf73844c2fcb79e8ea974f3464634fb2ceb has been merged into the auto branch https://github.com/karen-irc/popuko/commit/9e157790e976a39b911cb91e0fdbf96af16ade1c

**Comment by popuko** [comment]
:tada: success: The branch testing to merge this pull request into master has been succeed.

* [The Travis CI build passed](https://travis-ci.org/karen-irc/popuko/builds/189062102)

**Comment by popuko** [comment]
:hourglass: Try to merge 71214bf73844c2fcb79e8ea974f3464634fb2ceb

**Pull request merged**
