### PR TITLE
Add the option to start the application as TLS server.

### PR DESCRIPTION
**Pull request by saneyuki**
This change is [Reviewable](https://reviewable.io/reviews/karen-irc/popuko/176)

### CODE REVIEW

**Comment by saneyuki** [comment]
@popuko r+

**Comment by popuko** [comment]
:pushpin: Commit b09f1c02d118b936307289297a995db106ae97cd has been approved by `saneyuki`

**Comment by popuko** [comment]
:hourglass: b09f1c02d118b936307289297a995db106ae97cd has been merged into the auto branch e7cb0138717acf2ca150e54b2e02ebdedee9566c

**Comment by popuko** [comment]
:tada: The branch status which tried to merge this pull request into master is: success

* [The Travis CI build passed](https://travis-ci.org/karen-irc/popuko/builds/189578563)

**Pull request merged**
