### PR TITLE
Various clean up

### PR DESCRIPTION
**Pull request by saneyuki**
This change is [Reviewable](https://reviewable.io/reviews/karen-irc/popuko/179)

### CODE REVIEW

**Comment by saneyuki** [comment]
@popuko r+

**Comment by popuko** [comment]
:pushpin: Commit 20925afc4ac32e552cbed91016dbeb361656dc09 has been approved by `saneyuki`

**Comment by popuko** [comment]
:hourglass: 20925afc4ac32e552cbed91016dbeb361656dc09 has been merged into the auto branch 15f49ea55dc780832dab66cfb77b9932c4df1122

**Comment by popuko** [comment]
:tada: The branch status which tried to merge this pull request into master is: success

* [The Travis CI build passed](https://travis-ci.org/karen-irc/popuko/builds/189718493)

**Pull request merged**
