### PR TITLE
[demo] Write fot test

### PR DESCRIPTION
**Pull request by saneyuki**
Reverts karen-irc/popuko#122

### CODE REVIEW

**Comment by saneyuki** [comment]
@popuko r+

**Comment by popuko** [comment]
:pushpin: Commit 6c23d326896021950d051dc38ac17a1d1f8a8709 has been approved by `saneyuki`

**Comment by popuko** [comment]
:hourglass: 6c23d326896021950d051dc38ac17a1d1f8a8709 has been merged into the auto branch https://github.com/karen-irc/popuko/commit/48a1deef0b5643326d9cdb78e59eff868a514960

**Comment by popuko** [comment]
:tada: success: The branch testing to merge this pull request into master has been succeed.

* [The Travis CI build passed](https://travis-ci.org/karen-irc/popuko/builds/188760645)

**Comment by popuko** [comment]
:hourglass: Try to merge 6c23d326896021950d051dc38ac17a1d1f8a8709

**Pull request merged**
