### PR TITLE
Comment 'Merge Conflict' to the PR on try-to-patch-onto-auto

### PR DESCRIPTION
**Pull request by saneyuki**

### CODE REVIEW

**Comment by saneyuki** [comment]
@popuko r+

**Comment by popuko** [comment]
:pushpin: Commit 069dae032a18878da1c6c02c3bdc4ab28b20040f has been approved by `saneyuki`

**Comment by popuko** [comment]
:hourglass: 069dae032a18878da1c6c02c3bdc4ab28b20040f has been merged into the auto branch https://github.com/karen-irc/popuko/commit/4289ca41af9f4ca2b5a93b4989fe91ca363b04fc

**Comment by popuko** [comment]
:tada: success: The branch testing to merge this pull request into master has been succeed.

* [The Travis CI build passed](https://travis-ci.org/karen-irc/popuko/builds/188138336)

**Comment by popuko** [comment]
:hourglass: Try to merge 069dae032a18878da1c6c02c3bdc4ab28b20040f into `master`

**Pull request merged**
