### PR TITLE
Parse 'r? @bar-foo' correctly

### PR DESCRIPTION
**Pull request by saneyuki**
Fix https://github.com/karen-irc/popuko/issues/186

---
This change is [Reviewable](https://reviewable.io/reviews/karen-irc/popuko/188)

### CODE REVIEW

**Comment by saneyuki** [comment]
@popuko r+

**Comment by popuko** [comment]
:pushpin: Commit fb67bece9ed98230a70c0d9e8f4fe6d7cc7165bf has been approved by `saneyuki`

**Comment by popuko** [comment]
:hourglass: fb67bece9ed98230a70c0d9e8f4fe6d7cc7165bf has been merged into the auto branch 2cadd253ab1f8767d226eac680cd20c903c89f08

**Comment by popuko** [comment]
:tada: The result of what tried to merge this pull request is `success`.

* [The Travis CI build passed](https://travis-ci.org/karen-irc/popuko/builds/190915008)

**Pull request merged**
