### PR TITLE
[demo] update whitespace.txt

### PR DESCRIPTION
**Pull request by saneyuki**

### CODE REVIEW

**Comment by saneyuki** [comment]
@popuko r+

**Comment by popuko** [comment]
:hourglass: 0de3f5b9c426fcd93af82cb826532a523faacb43 has been merged into the auto branch https://github.com/karen-irc/popuko/commit/8b85af41452111c3cec08d65332bd4931f69b55f

**Comment by popuko** [comment]
:tada: success: The branch testing to merge this pull request into master has been succeed.

* [The Travis CI build passed](https://travis-ci.org/karen-irc/popuko/builds/189157385)

**Comment by popuko** [comment]
:hourglass: Try to merge 13e4faf44be54d5e96d9ae61d57a81579662ac84

**Comment by popuko** [comment]
:no_entry: The current head is changed from when this had been accepted. Please review again.

**Pull request closed without merging**
