### PR TITLE
Add 'Do you have any plan to support GitLab or GitHub Enterprise?' to README

### PR DESCRIPTION
**Pull request by saneyuki**
This change is [Reviewable](https://reviewable.io/reviews/karen-irc/popuko/174)

### CODE REVIEW

**Comment by saneyuki** [comment]
@popuko r+

**Comment by popuko** [comment]
:pushpin: Commit c8d8953dd6f0cad11493d8ea85113e55f08eeba1 has been approved by `saneyuki`

**Comment by popuko** [comment]
:hourglass: c8d8953dd6f0cad11493d8ea85113e55f08eeba1 has been merged into the auto branch 4dd3d60c1a3437d35a82a837526287838f5bf64a

**Comment by popuko** [comment]
:tada: The branch status which tried to merge this pull request into master is: success

* [The Travis CI build passed](https://travis-ci.org/karen-irc/popuko/builds/189559976)

**Pull request merged**
