### PR TITLE
Move setting object to settings/

### PR DESCRIPTION
**Pull request by saneyuki**

### CODE REVIEW

**Comment by saneyuki** [comment]
@popuko r+

**Comment by popuko** [comment]
:pushpin: Commit 8e808aa842a46ddb1365a1b68497c172326ec0a7 has been approved by `saneyuki`

**Comment by popuko** [comment]
:hourglass: 8e808aa842a46ddb1365a1b68497c172326ec0a7 has been merged into the auto branch https://github.com/karen-irc/popuko/commit/bc4653b5b93e8a8fe912e343eef7b112fd31dfa6

**Comment by popuko** [comment]
:tada: success: The branch testing to merge this pull request into master has been succeed.

* [The Travis CI build passed](https://travis-ci.org/karen-irc/popuko/builds/187387296)

**Comment by popuko** [comment]
:hourglass: Try to merge 8e808aa842a46ddb1365a1b68497c172326ec0a7 into `master`

**Pull request merged**
