### PR TITLE
Set the version of configuration

### PR DESCRIPTION
**Pull request by saneyuki**
This change is [Reviewable](https://reviewable.io/reviews/karen-irc/popuko/182)

### CODE REVIEW

**Comment by saneyuki** [comment]
@popuko r+

**Comment by popuko** [comment]
:pushpin: Commit fa106c8c9de8f83cdcad3d61a77f6d6585b893f6 has been approved by `saneyuki`

**Comment by popuko** [comment]
:hourglass: fa106c8c9de8f83cdcad3d61a77f6d6585b893f6 has been merged into the auto branch 78771ba95d20ca41ac017b252b7423ad859b8d9c

**Comment by popuko** [comment]
:tada: The result of what tried to merge this pull request is `success`.

* [The Travis CI build passed](https://travis-ci.org/karen-irc/popuko/builds/190515536)

**Pull request merged**
