### PR TITLE
Add the function trying the pull request with the latest master.

### PR DESCRIPTION
**Pull request by saneyuki**

### CODE REVIEW

**Comment by saneyuki** [comment]
@popuko r+

**Comment by popuko** [comment]
:pushpin: Commit eb521ae4baf9a2befe99626a10d49ca6d0b57955 has been approved by `saneyuki`

**Comment by popuko** [comment]
:hourglass: eb521ae4baf9a2befe99626a10d49ca6d0b57955 has been merged into the auto branch https://github.com/karen-irc/popuko/commit/6ddb9bbb67226703c601e4b6ca69e7510bab16d9

**Comment by popuko** [comment]
:tada: success: The branch testing to merge this pull request into master has been succeed.

* [The Travis CI build passed](https://travis-ci.org/karen-irc/popuko/builds/187327108)

**Comment by popuko** [comment]
:hourglass: Try to merge eb521ae4baf9a2befe99626a10d49ca6d0b57955 into `master`

**Pull request merged**
