### PR TITLE
Check the head's sha before mergeing the pull request

### PR DESCRIPTION
**Pull request by saneyuki**
https://github.com/karen-irc/popuko/issues/105

### CODE REVIEW

**Comment by saneyuki** [comment]
@popuko r+

**Comment by popuko** [comment]
:pushpin: Commit e18f608e745484739351e4b140078ac09d8305b1 has been approved by `saneyuki`

**Comment by popuko** [comment]
:hourglass: e18f608e745484739351e4b140078ac09d8305b1 has been merged into the auto branch https://github.com/karen-irc/popuko/commit/a569c84e73d88c2a44c38a41393a1420dcd56675

**Comment by popuko** [comment]
:tada: success: The branch testing to merge this pull request into master has been succeed.

* [The Travis CI build passed](https://travis-ci.org/karen-irc/popuko/builds/189158264)

**Comment by popuko** [comment]
:hourglass: Try to merge e18f608e745484739351e4b140078ac09d8305b1

**Comment by popuko** [comment]
:no_entry: The current head is changed from when this had been accepted. Please review again.

**Comment by saneyuki** [comment]
@popuko r+

**Comment by popuko** [comment]
:pushpin: Commit e18f608e745484739351e4b140078ac09d8305b1 has been approved by `saneyuki`

**Comment by popuko** [comment]
:hourglass: e18f608e745484739351e4b140078ac09d8305b1 has been merged into the auto branch https://github.com/karen-irc/popuko/commit/26b02057d907f6a7b68302ed24a57824d22e697a

**Comment by popuko** [comment]
:tada: success: The branch testing to merge this pull request into master has been succeed.

* [The Travis CI build passed](https://travis-ci.org/karen-irc/popuko/builds/189159581)

**Comment by popuko** [comment]
:hourglass: Try to merge e18f608e745484739351e4b140078ac09d8305b1

**Comment by popuko** [comment]
:no_entry: The current head is changed from when this had been accepted. Please review again.

**Comment by saneyuki** [comment]
@popuko r+

**Comment by popuko** [comment]
:pushpin: Commit e18f608e745484739351e4b140078ac09d8305b1 has been approved by `saneyuki`

**Comment by popuko** [comment]
:hourglass: e18f608e745484739351e4b140078ac09d8305b1 has been merged into the auto branch https://github.com/karen-irc/popuko/commit/6e750ee0098649d8010aa96af7c8d12ccbce4cbb

**Comment by saneyuki** [comment]
@popuko r+

**Comment by popuko** [comment]
:pushpin: Commit e18f608e745484739351e4b140078ac09d8305b1 has been approved by `saneyuki`

**Comment by popuko** [comment]
:hourglass: e18f608e745484739351e4b140078ac09d8305b1 has been merged into the auto branch https://github.com/karen-irc/popuko/commit/657a3f7cd7dcbb9981d00d56c790d1013c72b4d7

**Comment by popuko** [comment]
:tada: success: The branch testing to merge this pull request into master has been succeed.

* [The Travis CI build passed](https://travis-ci.org/karen-irc/popuko/builds/189162611)

**Comment by popuko** [comment]
:hourglass: Try to merge e18f608e745484739351e4b140078ac09d8305b1

**Pull request merged**
