### PR TITLE
[demo] Write fot test

### PR DESCRIPTION
**Pull request by saneyuki**

### CODE REVIEW

**Comment by saneyuki** [comment]
@popuko r+

**Comment by popuko** [comment]
:pushpin: Commit d96bcb8bfa0ecf01e1cbccc8d105684b4914ca01 has been approved by `saneyuki`

**Comment by popuko** [comment]
:hourglass: d96bcb8bfa0ecf01e1cbccc8d105684b4914ca01 has been merged into the auto branch https://github.com/karen-irc/popuko/commit/feb259026f3b9cb54863ac878f8ca9baecff0b31

**Comment by popuko** [comment]
:tada: success: The branch testing to merge this pull request into master has been succeed.

* [The Travis CI build passed](https://travis-ci.org/karen-irc/popuko/builds/188759345)

**Comment by popuko** [comment]
:hourglass: Try to merge d96bcb8bfa0ecf01e1cbccc8d105684b4914ca01

**Pull request merged**
