### PR TITLE
Move the config from in-binary-data to outside config file.

### PR DESCRIPTION
**Pull request by saneyuki**
## Related Issues

- Depend on #126

### CODE REVIEW

**Comment by popuko** [comment]
:umbrella: The latest upstream change (presumably [these](https://github.com/karen-irc/popuko/compare/24ecef48fe0d...8c4a73c9ca05)) made this pull request unmergeable. Please resolve the merge conflicts.

**Comment by saneyuki** [comment]
@popuko r+

**Comment by popuko** [comment]
:pushpin: Commit 737f778b2d891cc370d77cfca74945f40db16fb6 has been approved by `saneyuki`

**Comment by popuko** [comment]
:hourglass: 737f778b2d891cc370d77cfca74945f40db16fb6 has been merged into the auto branch https://github.com/karen-irc/popuko/commit/cc85eba87ae238de5f15d43dc5771fc3e274f5d7

**Comment by saneyuki** [comment]
@popuko r+

**Comment by popuko** [comment]
:pushpin: Commit 737f778b2d891cc370d77cfca74945f40db16fb6 has been approved by `saneyuki`

**Comment by popuko** [comment]
:hourglass: 737f778b2d891cc370d77cfca74945f40db16fb6 has been merged into the auto branch https://github.com/karen-irc/popuko/commit/3bb3686e6665b318e98086448cc88d6b3f0d650d

**Comment by popuko** [comment]
:collision: failure: The branch testing to merge this pull request into master has been troubled.

* [The Travis CI build failed](https://travis-ci.org/karen-irc/popuko/builds/189104629)

**Comment by saneyuki** [comment]
@popuko r+

**Comment by popuko** [comment]
:pushpin: Commit 737f778b2d891cc370d77cfca74945f40db16fb6 has been approved by `saneyuki`

**Comment by popuko** [comment]
:hourglass: 737f778b2d891cc370d77cfca74945f40db16fb6 has been merged into the auto branch https://github.com/karen-irc/popuko/commit/733e62be25fa8899814f2e6efe2d76fcd3ce06a7

**Comment by popuko** [comment]
:tada: success: The branch testing to merge this pull request into master has been succeed.

* [The Travis CI build passed](https://travis-ci.org/karen-irc/popuko/builds/189105193)

**Comment by popuko** [comment]
:hourglass: Try to merge 737f778b2d891cc370d77cfca74945f40db16fb6

**Pull request merged**
