### PR TITLE
Fix the regression by #209

### PR DESCRIPTION
**Pull request by saneyuki**
and various followup fixes.

---
This change is [Reviewable](https://reviewable.io/reviews/karen-irc/popuko/210)

### CODE REVIEW

**Comment by nekoya** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/karen-irc/popuko/210)*

**Comment by nekoya** [comment]
@popuko r+

**Comment by popuko** [comment]
:pushpin: Commit ae8e578f1664390c602823b84163b0ed1c179b49 has been approved by `nekoya`

**Comment by popuko** [comment]
:hourglass: ae8e578f1664390c602823b84163b0ed1c179b49 has been merged into the auto branch ca4ee7a1fa744e40e6255ef7d8975c9d406da8cd

**Comment by popuko** [comment]
:tada: The result of what tried to merge this pull request is `success`.

* [The Travis CI build passed](https://travis-ci.org/karen-irc/popuko/builds/194753418)

**Pull request merged**
