### PR TITLE
part 3: Implement a queue management to trying merging automatically.

### PR DESCRIPTION
**Pull request by saneyuki**
- https://github.com/nekoya/popuko/issues/45
- This changeset is very dirty. But This works correctly. I'll work to https://github.com/nekoya/popuko/issues/92 after this is merged.

### CODE REVIEW

**Comment by cynipe** [comment]
FYI http://folioscope.hatenablog.jp/entry/2015/11/25/213146

**Comment by saneyuki** [comment]
@nekoya r?

**Comment by saneyuki** [comment]
> FYI http://folioscope.hatenablog.jp/entry/2015/11/25/213146

@cynipe Thank you for your information!

By this link, we can know these points:

- GitHub create a ref `refs/pull/PR_NUM/merge` automatically.
  - GitHub's help document says same things: https://help.github.com/articles/checking-out-pull-requests-locally/
- And it always refers what the pull request is merged into the latest master.
- TravisCI uses this reference.

But we need kick by our hand to start to run a CI on its reference, we cannot have a convenient way to checking its reference just on before merging a pull request. Thus there is no change that we need to manage an pull request mergers by single queue as trying in #45.

I filed https://github.com/nekoya/popuko/issues/93 and we'll work this on it.

**Comment by saneyuki** [comment]
@nekoya r?

**Comment by saneyuki** [comment]
@nekoya r?

**Comment by nekoya** [comment]
@popuko r+

**Comment by popuko** [comment]
:pushpin: Commit d1dd0f46918bf557a324ed16d1b1736d871afdb0 has been approved by `nekoya`

**Comment by popuko** [comment]
:hourglass: d1dd0f46918bf557a324ed16d1b1736d871afdb0 has been merged into the auto branch https://github.com/karen-irc/popuko/commit/b2da1b8e5665624aafa1b0bcadfd3f5473d857d2

**Comment by popuko** [comment]
:tada: success: The branch testing to merge this pull request into master has been succeed.

* [The Travis CI build passed](https://travis-ci.org/karen-irc/popuko/builds/186732123)

**Comment by popuko** [comment]
:hourglass: Try to merge d1dd0f46918bf557a324ed16d1b1736d871afdb0 into `master`

**Pull request merged**
