### PR TITLE
part 4: Add file base persistent backend for auto merge queue

### PR DESCRIPTION
**Pull request by saneyuki**
- https://github.com/karen-irc/popuko/issues/45
- Fix https://github.com/karen-irc/popuko/issues/100

### CODE REVIEW

**Comment by saneyuki** [comment]
By this change,  we removes in-memory queue. We'll have only file base persistent backend.

This pull req. does not have any support to graceful shutdown.
If the app is shutdown when it is writing to file, then the file might be broken.
But you can recover it by your hand because the file is plain json!

**Comment by nekoya** [comment]
@popuko r+

**Comment by popuko** [comment]
:pushpin: Commit c910e084f458f1e8c9ef8515c259a26ccc9ceb7a has been approved by `nekoya`

**Comment by popuko** [comment]
:hourglass: c910e084f458f1e8c9ef8515c259a26ccc9ceb7a has been merged into the auto branch https://github.com/karen-irc/popuko/commit/9937b77144ef298c836397af7629e4b6bb732320

**Comment by popuko** [comment]
:tada: success: The branch testing to merge this pull request into master has been succeed.

* [The Travis CI build passed](https://travis-ci.org/karen-irc/popuko/builds/189084826)

**Pull request merged**
