### PR TITLE
Remove needless config field duplication about botname.

### PR DESCRIPTION
**Pull request by saneyuki**
This change is [Reviewable](https://reviewable.io/reviews/karen-irc/popuko/204)

### CODE REVIEW

**Comment by saneyuki** [comment]
@popuko r+

**Comment by popuko** [comment]
:pushpin: Commit 0dae982cfb7d653f65e126bcf2a6af3c961245e5 has been approved by `saneyuki`

**Comment by popuko** [comment]
:hourglass: 0dae982cfb7d653f65e126bcf2a6af3c961245e5 has been merged into the auto branch 09d0de16361b94d872f2b4e51830eac297387234

**Comment by popuko** [comment]
:collision: The result of what tried to merge this pull request is `failure`.

* [The Travis CI build failed](https://travis-ci.org/karen-irc/popuko/builds/192269681)

**Comment by popuko** [comment]
:pushpin: Commit ae80a32037b15b13519509b07dc8ce90b2f0d9c1 has been approved by `saneyuki`

**Comment by popuko** [comment]
:hourglass: ae80a32037b15b13519509b07dc8ce90b2f0d9c1 has been merged into the auto branch bb715f9d4f6063eba975e0dedfce4ec3f4727499

**Comment by popuko** [comment]
:tada: The result of what tried to merge this pull request is `success`.

* [The Travis CI build passed](https://travis-ci.org/karen-irc/popuko/builds/192270413)

**Pull request merged**
