### PR TITLE
Implement 'r-' command

### PR DESCRIPTION
**Pull request by saneyuki**
## Motivation

- This command can stop accepting a pull request which has been approved.
- This is a pair of `@<botname> r+`

## Details

- `@<botname> r-`
-  This command stop accepting a pull request which has been approved if the pull request has been approved & awaiting to merge into the upstream.
 

## Related issues.

- Fix https://github.com/karen-irc/popuko/issues/38

---
This change is [Reviewable](https://reviewable.io/reviews/karen-irc/popuko/157)

### CODE REVIEW

**Comment by popuko** [comment]
:umbrella: The latest upstream change (presumably [these](https://github.com/karen-irc/popuko/compare/9d3c6e19b9eb...d25f51866001)) made this pull request unmergeable. Please resolve the merge conflicts.

**Comment by saneyuki** [comment]
@popuko r+

**Comment by popuko** [comment]
:pushpin: Commit 60059593fb6f91fb91aa494b2a692c7a20e1fd1b has been approved by `saneyuki`

**Comment by saneyuki** [comment]
@popuko r-

**Comment by popuko** [comment]
:hourglass: 60059593fb6f91fb91aa494b2a692c7a20e1fd1b has been merged into the auto branch https://github.com/karen-irc/popuko/commit/1ae33feec51a8fa669f459bab06b873bec103660

**Comment by saneyuki** [comment]
@popuko r+

**Comment by popuko** [comment]
:pushpin: Commit db3b320146c71c65d4c1f3dbeeb414a24580608f has been approved by `saneyuki`

**Comment by saneyuki** [comment]
@popuko r-

**Comment by popuko** [comment]
:hourglass: db3b320146c71c65d4c1f3dbeeb414a24580608f has been merged into the auto branch https://github.com/karen-irc/popuko/commit/80dc340c7a78cd63e21ed33e977ca382c2d6e32e

**Comment by popuko** [comment]
:outbox_tray: This has been removed from the approved queue by `saneyuki`

**Comment by saneyuki** [comment]
Reviewed 9 of 9 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/karen-irc/popuko/157)*

**Comment by saneyuki** [comment]
Reviewed 6 of 6 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/karen-irc/popuko/157)*

**Comment by saneyuki** [comment]
@popuko r+

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/karen-irc/popuko/157#-:-K_m3gI-I2NI-JDfGSAN:b-spi8lm)*

**Comment by popuko** [comment]
:hourglass: ed0b0b74dce3b9e10faa8a3453eb0708dacc75b9 has been merged into the auto branch https://github.com/karen-irc/popuko/commit/f924c49f493667aa7fa5d1c541327ae09be5b827

**Comment by popuko** [comment]
:tada: success: The branch testing to merge this pull request into master has been succeed.

* [The Travis CI build passed](https://travis-ci.org/karen-irc/popuko/builds/189408666)

**Pull request merged**
