### PR TITLE
Fix the link to graydon's blog.

### PR DESCRIPTION
**Pull request by saneyuki**
This change is [Reviewable](https://reviewable.io/reviews/karen-irc/popuko/214)

### CODE REVIEW

**Comment by saneyuki** [comment]
@popuko r+

**Comment by popuko** [comment]
:pushpin: Commit fe65305af9907716b032e4db0d982ce0a3ef307f has been approved by `saneyuki`

**Comment by popuko** [comment]
:hourglass: fe65305af9907716b032e4db0d982ce0a3ef307f has been merged into the auto branch 709c37128b0d659a428f738b4bcd737e65631ed7

**Comment by popuko** [comment]
:tada: The result of what tried to merge this pull request is `success`.

* [The Travis CI build passed](https://travis-ci.org/karen-irc/popuko/builds/194870878)

**Pull request merged**
