### PR TITLE
Remove needless debug log

### PR DESCRIPTION
**Pull request by saneyuki**
This change is [Reviewable](https://reviewable.io/reviews/karen-irc/popuko/217)

### CODE REVIEW

**Comment by saneyuki** [comment]
@popuko r+

**Comment by popuko** [comment]
:pushpin: Commit b69c67fca053542c647a15102ece7ae16e162302 has been approved by `saneyuki`

**Comment by popuko** [comment]
:hourglass: b69c67fca053542c647a15102ece7ae16e162302 has been merged into the auto branch ff8e871ad38a2ca21da57c6d703a857bfd880b34

**Comment by popuko** [comment]
:tada: The result of what tried to merge this pull request is `success`.

* [The Travis CI build passed](https://travis-ci.org/karen-irc/popuko/builds/195073237)

**Pull request merged**
