### PR TITLE
Add the relation to Trunk Based Development

### PR DESCRIPTION
**Pull request by saneyuki**
This change is [Reviewable](https://reviewable.io/reviews/karen-irc/popuko/225)

### CODE REVIEW

**Comment by nekoya** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/karen-irc/popuko/225)*

**Comment by nekoya** [comment]
@popuko r+

**Comment by popuko** [comment]
:pushpin: Commit 8f9e81329982cada4e267665863d3d26b54f3302 has been approved by `nekoya`

**Comment by popuko** [comment]
:hourglass: 8f9e81329982cada4e267665863d3d26b54f3302 has been merged into the auto branch 0ce61f587d7d65739cfc05af60fcccab1a57c211

**Comment by popuko** [comment]
:tada: The result of what tried to merge this pull request is `success`.

* [The Travis CI build passed](https://travis-ci.org/karen-irc/popuko/builds/197168681)

**Pull request merged**
