### PR TITLE
Update github.com/google/go-github to de33c46a823d3f723514fc5333b75ef2e937b7df

### PR DESCRIPTION
**Pull request by saneyuki**
This is temporary fix. We should use `context` more correctly (https://github.com/karen-irc/popuko/issues/231)

---
This change is [Reviewable](https://reviewable.io/reviews/karen-irc/popuko/234)

### CODE REVIEW

**Comment by saneyuki** [comment]
@popuko r+

**Comment by saneyuki** [comment]
@popuko r-

**Comment by saneyuki** [comment]
> This is temporary fix. We should use context more correctly (#231)

We need to fix it 😢

**Comment by saneyuki** [comment]
@popuko r+

**Comment by popuko** [comment]
:pushpin: Commit 72d5eafd948ca2afd4035a0dd6662dd425021001 has been approved by `saneyuki`

**Comment by popuko** [comment]
:hourglass: 72d5eafd948ca2afd4035a0dd6662dd425021001 has been merged into the auto branch 45a976f586602b6df6f8648d04a9c6a051f8788f

**Comment by popuko** [comment]
:tada: The result of what tried to merge this pull request is `success`.

* [The Travis CI build passed](https://travis-ci.org/karen-irc/popuko/builds/221987399)

**Pull request merged**
