### PR TITLE
[demo] edit whitespace

### PR DESCRIPTION
**Pull request by saneyuki**
This change is [Reviewable](https://reviewable.io/reviews/karen-irc/popuko/200)

### CODE REVIEW

**Comment by saneyuki** [comment]
@popuko r+

**Comment by popuko** [comment]
:pushpin: Commit 347e5e75fba2453d1f8459e79dc11b3f911ed1cc has been approved by `saneyuki`

**Comment by popuko** [comment]
:hourglass: 347e5e75fba2453d1f8459e79dc11b3f911ed1cc has been merged into the auto branch b70b28da9b65c7ea62eaa6bd219694ceb7a1df10

**Comment by popuko** [comment]
:tada: The result of what tried to merge this pull request is `success`.

* [The Travis CI build passed](https://travis-ci.org/karen-irc/popuko/builds/192081127)

**Pull request merged**
