### PR TITLE
Check whether the input string is valid to prevent directory traversal attack

### PR DESCRIPTION
**Pull request by saneyuki**
This change is [Reviewable](https://reviewable.io/reviews/karen-irc/popuko/209)

### CODE REVIEW

**Comment by nekoya** [comment]
Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/karen-irc/popuko/209)*

**Comment by nekoya** [comment]
@popuko r+

**Comment by popuko** [comment]
:pushpin: Commit 5396e7be59179ddb73833b9090057f3b2bfa07e2 has been approved by `nekoya`

**Comment by popuko** [comment]
:hourglass: 5396e7be59179ddb73833b9090057f3b2bfa07e2 has been merged into the auto branch 55bbe85e4cfe23051e56beefd628f1de17cdf40a

**Comment by popuko** [comment]
:tada: The result of what tried to merge this pull request is `success`.

* [The Travis CI build passed](https://travis-ci.org/karen-irc/popuko/builds/194691527)

**Comment by nekoya** [comment]
All repositories works with Popuko are registered by the bot owner.

However, anyone can kick the web hook URL, indeed. This protection was required.

**Pull request merged**
