### PR TITLE
[demo] test

### PR DESCRIPTION
**Pull request by saneyuki**
This change is [Reviewable](https://reviewable.io/reviews/karen-irc/popuko/208)

### CODE REVIEW

**Comment by saneyuki** [comment]
@popuko r=Constellation

**Comment by popuko** [comment]
:pushpin: Commit a1adffd77cedd68f24a676993eeb10f6ef78d8ed has been approved by , `Constellation`

**Comment by popuko** [comment]
:hourglass: a1adffd77cedd68f24a676993eeb10f6ef78d8ed has been merged into the auto branch efae67f6e8f0f4baf8e4164d1bce6350adb1c82e

**Comment by saneyuki** [comment]
@popuko r-

**Comment by popuko** [comment]
:outbox_tray: This has been cancelled from the approved queue by `saneyuki`

**Comment by saneyuki** [comment]
@popuko r=Constellation, barfoo

**Comment by popuko** [comment]
:pushpin: Commit a1adffd77cedd68f24a676993eeb10f6ef78d8ed has been approved by `Constellation`, `barfoo`

**Comment by popuko** [comment]
:hourglass: a1adffd77cedd68f24a676993eeb10f6ef78d8ed has been merged into the auto branch efae67f6e8f0f4baf8e4164d1bce6350adb1c82e

**Comment by saneyuki** [comment]
@popuko r-

**Comment by popuko** [comment]
:outbox_tray: This has been cancelled from the approved queue by `saneyuki`

**Comment by saneyuki** [comment]
@popuko r+

**Comment by popuko** [comment]
:pushpin: Commit a1adffd77cedd68f24a676993eeb10f6ef78d8ed has been approved by `saneyuki`

**Comment by popuko** [comment]
:hourglass: a1adffd77cedd68f24a676993eeb10f6ef78d8ed has been merged into the auto branch efae67f6e8f0f4baf8e4164d1bce6350adb1c82e

**Comment by saneyuki** [comment]
@popuko r-

**Comment by popuko** [comment]
:outbox_tray: This has been cancelled from the approved queue by `saneyuki`

**Pull request closed without merging**
