### PR TITLE
Revert "[demo] Write fot test"

### PR DESCRIPTION
**Pull request by saneyuki**
Reverts karen-irc/popuko#123

### CODE REVIEW

**Comment by saneyuki** [comment]
@popuko r+

**Comment by popuko** [comment]
:pushpin: Commit 8bceb4b3c3a96ee6e1d8a4ae9171f73f94976495 has been approved by `saneyuki`

**Comment by popuko** [comment]
:hourglass: 8bceb4b3c3a96ee6e1d8a4ae9171f73f94976495 has been merged into the auto branch https://github.com/karen-irc/popuko/commit/4b9618304ef57aeedf47293482610b88e4022946

**Comment by popuko** [comment]
:tada: success: The branch testing to merge this pull request into master has been succeed.

* [The Travis CI build passed](https://travis-ci.org/karen-irc/popuko/builds/188761156)

**Comment by popuko** [comment]
:hourglass: Try to merge 8bceb4b3c3a96ee6e1d8a4ae9171f73f94976495

**Pull request merged**
