### PR TITLE
Stop to nil dereference

### PR DESCRIPTION
**Pull request by saneyuki**

### CODE REVIEW

**Comment by saneyuki** [comment]
@popuko r+

**Comment by popuko** [comment]
:pushpin: Commit fa1d329251a7ace7c62b07390049f7077774e9d4 has been approved by `saneyuki`

**Comment by saneyuki** [comment]
@popuko r+

**Comment by popuko** [comment]
:pushpin: Commit fa1d329251a7ace7c62b07390049f7077774e9d4 has been approved by `saneyuki`

**Comment by popuko** [comment]
:hourglass: fa1d329251a7ace7c62b07390049f7077774e9d4 has been merged into the auto branch https://github.com/karen-irc/popuko/commit/8d79deea161f001c78508ac7014469464c3c4161

**Comment by popuko** [comment]
:tada: success: The branch testing to merge this pull request into master has been succeed.

* [The Travis CI build passed](https://travis-ci.org/karen-irc/popuko/builds/188749552)

**Comment by popuko** [comment]
:hourglass: Try to merge fa1d329251a7ace7c62b07390049f7077774e9d4 into `master`

**Pull request merged**
