### PR TITLE
Move IsIncludeAutoBranch to operation/

### PR DESCRIPTION
**Pull request by saneyuki**

### CODE REVIEW

**Comment by saneyuki** [comment]
@popuko +

**Comment by saneyuki** [comment]
@popuko r+

**Comment by popuko** [comment]
:pushpin: Commit 0d1a3ffd37566bff6233d3ec8b1796f51142eebf has been approved by `saneyuki`

**Comment by popuko** [comment]
:hourglass: 0d1a3ffd37566bff6233d3ec8b1796f51142eebf has been merged into the auto branch https://github.com/karen-irc/popuko/commit/8f4b9216848ed27af63cef383198261792497feb

**Comment by popuko** [comment]
:tada: success: The branch testing to merge this pull request into master has been succeed.

* [The Travis CI build passed](https://travis-ci.org/karen-irc/popuko/builds/189059711)

**Comment by popuko** [comment]
:hourglass: Try to merge 0d1a3ffd37566bff6233d3ec8b1796f51142eebf

**Pull request merged**
