### PR TITLE
Care the case which 'r+' to the pull request has been approved again.

### PR DESCRIPTION
**Pull request by saneyuki**
This change is [Reviewable](https://reviewable.io/reviews/karen-irc/popuko/163)

### CODE REVIEW

**Comment by saneyuki** [comment]
@nekoya r?

**Comment by nekoya** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/karen-irc/popuko/163)*

**Comment by nekoya** [comment]
@popuko r+

**Comment by popuko** [comment]
:pushpin: Commit 83facaefc197ee1089a3feb6c506d67c9a83aa12 has been approved by `nekoya`

**Comment by popuko** [comment]
:hourglass: 83facaefc197ee1089a3feb6c506d67c9a83aa12 has been merged into the auto branch 4a08abfbe5805e4ab3b469f5023745c57d022c88

**Comment by popuko** [comment]
:tada: success: The branch testing to merge this pull request into master has been succeed.

* [The Travis CI build passed](https://travis-ci.org/karen-irc/popuko/builds/189438467)

**Pull request merged**
