### PR TITLE
Change the type of AutoMergeQueueItem.SHA

### PR DESCRIPTION
**Pull request by saneyuki**
This is ensured to be string.

### CODE REVIEW

**Comment by saneyuki** [comment]
@popuko r+

**Comment by popuko** [comment]
:pushpin: Commit 39cbb6dd32d1da6393d1252709b51e785d895998 has been approved by `saneyuki`

**Comment by popuko** [comment]
:tada: success: The branch testing to merge this pull request into master has been succeed.

* [The Travis CI build passed](https://travis-ci.org/karen-irc/popuko/builds/189150344)

**Comment by popuko** [comment]
:hourglass: Try to merge 39cbb6dd32d1da6393d1252709b51e785d895998

**Pull request merged**
