### PR TITLE
Stop to mis-detects "unmergeable" pull request if the upstream has been changed.

### PR DESCRIPTION
**Pull request by saneyuki**
Fix https://github.com/karen-irc/popuko/issues/187

---
This change is [Reviewable](https://reviewable.io/reviews/karen-irc/popuko/202)

### CODE REVIEW

**Comment by nekoya** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/karen-irc/popuko/202)*

**Comment by nekoya** [comment]
@popuko r+

**Comment by popuko** [comment]
:pushpin: Commit 89f1af5929a46469eaedd05cac3d279d450c2007 has been approved by `nekoya`

**Comment by popuko** [comment]
:hourglass: 89f1af5929a46469eaedd05cac3d279d450c2007 has been merged into the auto branch 290eb62f5f53c1e9de574b4309e2bcbf377adee7

**Comment by popuko** [comment]
:tada: The result of what tried to merge this pull request is `success`.

* [The Travis CI build passed](https://travis-ci.org/karen-irc/popuko/builds/198798432)

**Pull request merged**
