### PR TITLE
Revert "Revert "[demo] Write fot test""

### PR DESCRIPTION
**Pull request by saneyuki**
Reverts karen-irc/popuko#124

### CODE REVIEW

**Comment by saneyuki** [comment]
@popuko r+

**Comment by popuko** [comment]
:pushpin: Commit 4cff5c9f3d0129d1f029ee0ab3347b378f5cfa04 has been approved by `saneyuki`

**Comment by popuko** [comment]
:hourglass: 4cff5c9f3d0129d1f029ee0ab3347b378f5cfa04 has been merged into the auto branch https://github.com/karen-irc/popuko/commit/e01dcf5fa18315051482fc89f6420f752b8bd1cc

**Comment by popuko** [comment]
:tada: success: The branch testing to merge this pull request into master has been succeed.

* [The Travis CI build passed](https://travis-ci.org/karen-irc/popuko/builds/188764397)

**Comment by popuko** [comment]
:hourglass: Try to merge 4cff5c9f3d0129d1f029ee0ab3347b378f5cfa04

**Pull request merged**
