### PR TITLE
Rename the serialized name of AutoMergeQueueItem.AutoBranchHead

### PR DESCRIPTION
**Pull request by saneyuki**
This change is [Reviewable](https://reviewable.io/reviews/karen-irc/popuko/169)

### CODE REVIEW

**Comment by saneyuki** [comment]
@popuko r+

**Comment by popuko** [comment]
:pushpin: Commit 8c771531ed08c216edc75bfc2f844c3eb3fe58c1 has been approved by `saneyuki`

**Comment by popuko** [comment]
:hourglass: 8c771531ed08c216edc75bfc2f844c3eb3fe58c1 has been merged into the auto branch 14cda907cd3175069e4b5431003ba0b0b531ea16

**Comment by popuko** [comment]
:tada: The branch status which tried to merge this pull request into master is: success

* [The Travis CI build passed](https://travis-ci.org/karen-irc/popuko/builds/189459015)

**Pull request merged**
