### PR TITLE
Do not close the pull request if the merge operation was failed.

### PR DESCRIPTION
**Pull request by saneyuki**
This change is [Reviewable](https://reviewable.io/reviews/karen-irc/popuko/162)

### CODE REVIEW

**Comment by saneyuki** [comment]
@popuko r+

**Comment by popuko** [comment]
:pushpin: Commit 2628136b4fde482a2e9b4d4a1bd8b523ecdcac05 has been approved by `saneyuki`

**Comment by popuko** [comment]
:hourglass: 2628136b4fde482a2e9b4d4a1bd8b523ecdcac05 has been merged into the auto branch d3630df2f8251a133d00b74e5b9cfdddb328fdc1

**Comment by popuko** [comment]
:tada: success: The branch testing to merge this pull request into master has been succeed.

* [The Travis CI build passed](https://travis-ci.org/karen-irc/popuko/builds/189418879)

**Pull request merged**
