### PR TITLE
[demo] update whitespace.txt

### PR DESCRIPTION
**Pull request by saneyuki**

### CODE REVIEW

**Comment by saneyuki** [comment]
@popuko r+

**Comment by popuko** [comment]
:hourglass: 83359d979dd4a603bfad5f4f85a5b9b04ef47452 has been merged into the auto branch https://github.com/karen-irc/popuko/commit/35e39420f6bdd655622e5a6b6362483029e3f5e7

**Comment by popuko** [comment]
:pushpin: Commit 83359d979dd4a603bfad5f4f85a5b9b04ef47452 has been approved by `saneyuki`

**Comment by popuko** [comment]
:hourglass: 83359d979dd4a603bfad5f4f85a5b9b04ef47452 has been merged into the auto branch https://github.com/karen-irc/popuko/commit/b4d5ddd980ffaa2c3cc996473d7a0aa9b3b2ff55

**Comment by popuko** [comment]
:hourglass: Try to merge 83359d979dd4a603bfad5f4f85a5b9b04ef47452

**Pull request merged**
