### PR TITLE
Not comment 'Try to merge <sha> before merging the pr'

### PR DESCRIPTION
**Pull request by saneyuki**

### CODE REVIEW

**Comment by saneyuki** [comment]
@popuko r+

**Comment by popuko** [comment]
:pushpin: Commit 532b4fcd7ea596f9baf77618b85353ee1c812775 has been approved by `saneyuki`

**Comment by popuko** [comment]
:hourglass: 532b4fcd7ea596f9baf77618b85353ee1c812775 has been merged into the auto branch https://github.com/karen-irc/popuko/commit/ef16e04fabcdd112f28dc682d449835f6ccd0a2a

**Comment by popuko** [comment]
:tada: success: The branch testing to merge this pull request into master has been succeed.

* [The Travis CI build passed](https://travis-ci.org/karen-irc/popuko/builds/189164081)

**Comment by popuko** [comment]
:no_entry: The current head is changed from when this had been accepted. Please review again.

**Comment by saneyuki** [comment]
@popuko r+

**Comment by popuko** [comment]
:pushpin: Commit 16a499adcfda65bb6ddc7f4b9534b7065246cf87 has been approved by `saneyuki`

**Pull request merged**
