### PR TITLE
Create the backup file on writing a queue to the file

### PR DESCRIPTION
**Pull request by saneyuki**
If the application fails down when it is writing to the file, the content of its file may be wrecked.

To resolve it, we use the following steps when we write a content to the
file:

1. Creare the backup file by renaming the file to `***.old`.
2. Write a content to the file.
3. Remove the file created in steps 1).

As alternative approach, we could implement a graceful shutdown for this.  But we thought it is hard to implement it correctly. So we don't accept its approach at this moment.

## Related Issues

- Depend on https://github.com/karen-irc/popuko/pull/126

### CODE REVIEW

**Comment by saneyuki** [comment]
@popuko r+

**Comment by popuko** [comment]
:pushpin: Commit cf9d03b4b1753039a5db4aab2441f28f2421d07d has been approved by `saneyuki`

**Comment by popuko** [comment]
:hourglass: cf9d03b4b1753039a5db4aab2441f28f2421d07d has been merged into the auto branch https://github.com/karen-irc/popuko/commit/3031b4ab75ad9c360a776972c18291cca7280455

**Comment by saneyuki** [comment]
@popuko r+

**Comment by popuko** [comment]
:pushpin: Commit cf9d03b4b1753039a5db4aab2441f28f2421d07d has been approved by `saneyuki`

**Comment by popuko** [comment]
:hourglass: cf9d03b4b1753039a5db4aab2441f28f2421d07d has been merged into the auto branch https://github.com/karen-irc/popuko/commit/b4611d17aa8b1826eab8e5ccc88ce8e092fa96a8

**Comment by saneyuki** [comment]
@popuko r+

**Comment by popuko** [comment]
:pushpin: Commit cf9d03b4b1753039a5db4aab2441f28f2421d07d has been approved by `saneyuki`

**Comment by popuko** [comment]
:postbox: This pull request is queued. Please await the time.

**Comment by saneyuki** [comment]
@popuko r+

**Comment by popuko** [comment]
:pushpin: Commit cf9d03b4b1753039a5db4aab2441f28f2421d07d has been approved by `saneyuki`

**Comment by popuko** [comment]
:postbox: This pull request is queued. Please await the time.

**Comment by saneyuki** [comment]
@popuko r+

**Comment by popuko** [comment]
:pushpin: Commit cf9d03b4b1753039a5db4aab2441f28f2421d07d has been approved by `saneyuki`

**Comment by popuko** [comment]
:postbox: This pull request is queued. Please await the time.

**Comment by saneyuki** [comment]
@popuko r+

**Comment by popuko** [comment]
:pushpin: Commit cf9d03b4b1753039a5db4aab2441f28f2421d07d has been approved by `saneyuki`

**Comment by popuko** [comment]
:postbox: This pull request is queued. Please await the time.

**Comment by popuko** [comment]
:hourglass: cf9d03b4b1753039a5db4aab2441f28f2421d07d has been merged into the auto branch https://github.com/karen-irc/popuko/commit/b58be6a4d7be9a8e1525efb6819efed9621fe972

**Comment by popuko** [comment]
:tada: success: The branch testing to merge this pull request into master has been succeed.

* [The Travis CI build passed](https://travis-ci.org/karen-irc/popuko/builds/189134941)

**Comment by popuko** [comment]
:hourglass: Try to merge cf9d03b4b1753039a5db4aab2441f28f2421d07d

**Pull request merged**
