### PR TITLE
Use tryNextItem in the path for accepting changeset

### PR DESCRIPTION
**Pull request by saneyuki**
This change is [Reviewable](https://reviewable.io/reviews/karen-irc/popuko/178)

### CODE REVIEW

**Comment by saneyuki** [comment]
@popuko r+

**Comment by popuko** [comment]
:pushpin: Commit 027cfaabdc86f2821e9ad73dd0bf8c38cf8a24b5 has been approved by `saneyuki`

**Comment by popuko** [comment]
:hourglass: 027cfaabdc86f2821e9ad73dd0bf8c38cf8a24b5 has been merged into the auto branch 40a4316b1934433a402bebf8ad38b81731004d3b

**Comment by popuko** [comment]
:tada: The branch status which tried to merge this pull request into master is: success

* [The Travis CI build passed](https://travis-ci.org/karen-irc/popuko/builds/189583118)

**Pull request merged**
