### PR TITLE
Rewrite the setup instruction

### PR DESCRIPTION
**Pull request by saneyuki**
Fix https://github.com/karen-irc/popuko/issues/103

---
This change is [Reviewable](https://reviewable.io/reviews/karen-irc/popuko/167)

### CODE REVIEW

**Comment by saneyuki** [comment]
@nekoya r?

**Comment by nekoya** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[README.md, line 50 at r1](https://reviewable.io:443/reviews/karen-irc/popuko/167#-K_n04gkVvR6eIeJDRFq:-K_n04gkVvR6eIeJDRFr:bmqdm22) ([raw file](https://github.com/karen-irc/popuko/blob/745b6a52afc5f9629d9d891acbce5e8d5879a499/README.md#L50)):*
> -config-base-dir

In this case, `--config-case-dir` also works. Which is more appropriate description at golang world ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/karen-irc/popuko/167)*

**Comment by saneyuki** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[README.md, line 50 at r1](https://reviewable.io:443/reviews/karen-irc/popuko/167#-K_n04gkVvR6eIeJDRFq:-K_nBVadBKMsQpqVSWNf:b-ibrzmg) ([raw file](https://github.com/karen-irc/popuko/blob/745b6a52afc5f9629d9d891acbce5e8d5879a499/README.md#L50)):*
<details><summary><i>Previously, nekoya (Ryo Miyake) wrote…</i></summary><blockquote>

> -config-base-dir

In this case, `--config-case-dir` also works. Which is more appropriate description at golang world ?
</blockquote></details>

Ah, it works correctly. I'll fix this document.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/karen-irc/popuko/167)*

**Comment by nekoya** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/karen-irc/popuko/167)*

**Comment by nekoya** [comment]
@popuko r+

**Comment by popuko** [comment]
:pushpin: Commit 85b9f685b695b53cf328776a9e85173081e0fc5c has been approved by `nekoya`

**Comment by popuko** [comment]
:hourglass: 85b9f685b695b53cf328776a9e85173081e0fc5c has been merged into the auto branch 893362e89d1581a1e980f25ac8424fb3256cff11

**Comment by saneyuki** [comment]
@popuko r+

**Comment by popuko** [comment]
:pushpin: Commit 85b9f685b695b53cf328776a9e85173081e0fc5c has been approved by `saneyuki`

**Comment by popuko** [comment]
:hourglass: 85b9f685b695b53cf328776a9e85173081e0fc5c has been merged into the auto branch 893362e89d1581a1e980f25ac8424fb3256cff11

**Comment by popuko** [comment]
:collision: The branch status which tried to merge this pull request into master is: error

* [The Travis CI build could not complete due to an error](https://travis-ci.org/karen-irc/popuko/builds/189461170)

**Comment by saneyuki** [comment]
@popuko r+

**Comment by popuko** [comment]
:pushpin: Commit 85b9f685b695b53cf328776a9e85173081e0fc5c has been approved by `saneyuki`

**Comment by popuko** [comment]
:hourglass: 85b9f685b695b53cf328776a9e85173081e0fc5c has been merged into the auto branch 893362e89d1581a1e980f25ac8424fb3256cff11

**Comment by popuko** [comment]
:tada: The branch status which tried to merge this pull request into master is: success

* [The Travis CI build passed](https://travis-ci.org/karen-irc/popuko/builds/189461390)

**Pull request merged**
