### PR TITLE
Add the answer to 'Why didn't you fork homu?'

### PR DESCRIPTION
**Pull request by saneyuki**
This change is [Reviewable](https://reviewable.io/reviews/karen-irc/popuko/180)

### CODE REVIEW

**Comment by saneyuki** [comment]
@nekoya r?

**Comment by nekoya** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/karen-irc/popuko/180)*

**Comment by nekoya** [comment]
@popuko r+

**Comment by popuko** [comment]
:pushpin: Commit 2648f1abf00c1c5cc0d543158f68741599b05164 has been approved by `nekoya`

**Comment by popuko** [comment]
:postbox: This pull request is queued. Please await the time.

**Comment by saneyuki** [comment]
@popuko r=nekoya

**Comment by popuko** [comment]
:pushpin: Commit 2648f1abf00c1c5cc0d543158f68741599b05164 has been approved by `saneyuki`

**Comment by popuko** [comment]
:hourglass: 2648f1abf00c1c5cc0d543158f68741599b05164 has been merged into the auto branch 289d1f877d47143e7b65fa526712a3f60bcf07bd

**Comment by popuko** [comment]
:tada: The result of what tried to merge this pull request is `success`.

* [The Travis CI build passed](https://travis-ci.org/karen-irc/popuko/builds/190481467)

**Pull request merged**
