### PR TITLE
Accept 'created' issue comment event only

### PR DESCRIPTION
**Pull request by saneyuki**
This change is [Reviewable](https://reviewable.io/reviews/karen-irc/popuko/215)

### CODE REVIEW

**Comment by saneyuki** [comment]
@popuko r+

**Comment by popuko** [comment]
:pushpin: Commit 457a63395b654f6ef016dc79d19241554574fbc4 has been approved by `saneyuki`

**Comment by popuko** [comment]
:hourglass: 457a63395b654f6ef016dc79d19241554574fbc4 has been merged into the auto branch 21e7b2c8e1d0c653fdcb59b622299ff1eb99c05a

**Comment by popuko** [comment]
:tada: The result of what tried to merge this pull request is `success`.

* [The Travis CI build passed](https://travis-ci.org/karen-irc/popuko/builds/194883094)

**Pull request merged**
