### PR TITLE
Remove all status (`S-` prefixed) labels after a pull request is closed

### PR DESCRIPTION
**Pull request by saneyuki**
This change is [Reviewable](https://reviewable.io/reviews/karen-irc/popuko/228)

### CODE REVIEW

**Comment by nekoya** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/karen-irc/popuko/228)*

**Comment by nekoya** [comment]
@popuko r+

**Comment by popuko** [comment]
:pushpin: Commit c2a58514fc0c388aa24bf4a098affc5458bb4206 has been approved by `nekoya`

**Comment by popuko** [comment]
:hourglass: c2a58514fc0c388aa24bf4a098affc5458bb4206 has been merged into the auto branch 7049dd93adcf8c5b18f417c9002664b9226e7d09

**Comment by popuko** [comment]
:tada: The result of what tried to merge this pull request is `success`.

* [The Travis CI build passed](https://travis-ci.org/karen-irc/popuko/builds/202138928)

**Pull request merged**
