### PR TITLE
[demo] for testing

### PR DESCRIPTION
**Pull request by saneyuki**
This change is [Reviewable](https://reviewable.io/reviews/karen-irc/popuko/222)

### CODE REVIEW

**Comment by saneyuki** [comment]
@popuko r+

**Comment by popuko** [comment]
:pushpin: Commit f3c13b91233d1753c2320cff7b9fd2e56b9df0bb has been approved by `saneyuki`

**Comment by popuko** [comment]
:hourglass: f3c13b91233d1753c2320cff7b9fd2e56b9df0bb has been merged into the auto branch 0f85674c02d93242a1e2c2a1a9eabb1f19f6c7bb

**Comment by popuko** [comment]
:tada: The result of what tried to merge this pull request is `success`.

* [The Travis CI build passed](https://travis-ci.org/karen-irc/popuko/builds/195502129)

**Pull request merged**
