### PR TITLE
Move label related oprations to operation/

### PR DESCRIPTION
**Pull request by saneyuki**

### CODE REVIEW

**Comment by saneyuki** [comment]
@popuko r+

**Comment by popuko** [comment]
:pushpin: Commit 5500a013d27b4e6aa6c1c5e9b5c2480cfc485816 has been approved by `saneyuki`

**Comment by popuko** [comment]
:hourglass: 5500a013d27b4e6aa6c1c5e9b5c2480cfc485816 has been merged into the auto branch https://github.com/karen-irc/popuko/commit/3aa5a0d3656c3e679c45fbc3c8ab1664e67fd044

**Comment by popuko** [comment]
:tada: success: The branch testing to merge this pull request into master has been succeed.

* [The Travis CI build passed](https://travis-ci.org/karen-irc/popuko/builds/187389736)

**Comment by popuko** [comment]
:hourglass: Try to merge 5500a013d27b4e6aa6c1c5e9b5c2480cfc485816 into `master`

**Pull request merged**
