### PR TITLE
Move queue.go to under queue/

### PR DESCRIPTION
**Pull request by saneyuki**

### CODE REVIEW

**Comment by saneyuki** [comment]
@popuko r+

**Comment by popuko** [comment]
:pushpin: Commit 82decfc9ddcdaaaa3dc95726988084cb6aeed608 has been approved by `saneyuki`

**Comment by popuko** [comment]
:hourglass: 82decfc9ddcdaaaa3dc95726988084cb6aeed608 has been merged into the auto branch https://github.com/karen-irc/popuko/commit/4d8fa9c326f284343dd9ddd181a616ca8dffb86a

**Comment by popuko** [comment]
:tada: success: The branch testing to merge this pull request into master has been succeed.

* [The Travis CI build passed](https://travis-ci.org/karen-irc/popuko/builds/188140032)

**Comment by popuko** [comment]
:hourglass: Try to merge 82decfc9ddcdaaaa3dc95726988084cb6aeed608 into `master`

**Pull request merged**
