### PR TITLE
Add the abstract operation function to write a comment to an issue.

### PR DESCRIPTION
**Pull request by saneyuki**

### CODE REVIEW

**Comment by saneyuki** [comment]
@popuko r+

**Comment by popuko** [comment]
:pushpin: Commit 2f7040d6c653897e542aa6a09e8033ffcf9256dd has been approved by `saneyuki`

**Comment by popuko** [comment]
:hourglass: 2f7040d6c653897e542aa6a09e8033ffcf9256dd has been merged into the auto branch https://github.com/karen-irc/popuko/commit/29167b1f5c29486f4afe69ecbf691bfe6e7b9184

**Comment by popuko** [comment]
:tada: success: The branch testing to merge this pull request into master has been succeed.

* [The Travis CI build passed](https://travis-ci.org/karen-irc/popuko/builds/187298218)

**Comment by popuko** [comment]
:hourglass: Try to merge 2f7040d6c653897e542aa6a09e8033ffcf9256dd into `master`

**Pull request merged**
