### PR TITLE
Comment an actual reviewer by 'r=reviewer'

### PR DESCRIPTION
**Pull request by saneyuki**
- Fix https://github.com/karen-irc/popuko/issues/106
- By this change, we allow non-reviewer name to `r=<reviewer>`. But an only reviewer can ignite this command. It's not changed.

---
This change is [Reviewable](https://reviewable.io/reviews/karen-irc/popuko/207)

### CODE REVIEW

**Comment by saneyuki** [comment]
@nekoya r?

**Comment by nekoya** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/karen-irc/popuko/207)*

**Comment by nekoya** [comment]
@popuko r+

**Comment by popuko** [comment]
:pushpin: Commit 7f714a0f90459067587a58410e63226a7b321745 has been approved by `nekoya`

**Comment by popuko** [comment]
:hourglass: 7f714a0f90459067587a58410e63226a7b321745 has been merged into the auto branch 93f93e0cce391dbe026b416aa23fc81ab58c0b49

**Comment by popuko** [comment]
:tada: The result of what tried to merge this pull request is `success`.

* [The Travis CI build passed](https://travis-ci.org/karen-irc/popuko/builds/194389686)

**Pull request merged**
