### PR TITLE
Refactor Merging Pull Request

### PR DESCRIPTION
**Pull request by saneyuki**

### CODE REVIEW

**Comment by saneyuki** [comment]
@popuko r+

**Comment by popuko** [comment]
:pushpin: Commit aa705ff6a7a3575da2663d9b249437b8ec3ef95e has been approved by `saneyuki`

**Comment by popuko** [comment]
:tada: success: The branch testing to merge this pull request into master has been succeed.

* [The Travis CI build passed](https://travis-ci.org/karen-irc/popuko/builds/187380364)

**Comment by popuko** [comment]
:hourglass: Try to merge aa705ff6a7a3575da2663d9b249437b8ec3ef95e into `master`

**Pull request merged**
