### PR TITLE
Update "The current limitations" of README

### PR DESCRIPTION
**Pull request by saneyuki**
Today, we use `refs/pull/PR/merge` to create an `auto` branch. There is no limitations about "Auto-Merging".

---
This change is [Reviewable](https://reviewable.io/reviews/karen-irc/popuko/191)

### CODE REVIEW

**Comment by saneyuki** [comment]
@popuko +

**Comment by saneyuki** [comment]
@popuko r+

**Comment by popuko** [comment]
:pushpin: Commit 3098b2a7133f567b56b4c869b87e665b70b63fbf has been approved by `saneyuki`

**Comment by popuko** [comment]
:hourglass: 3098b2a7133f567b56b4c869b87e665b70b63fbf has been merged into the auto branch 9b750126c666d5be13b3d3fa56f3c4d9395df8c7

**Comment by popuko** [comment]
:tada: The result of what tried to merge this pull request is `success`.

* [The Travis CI build passed](https://travis-ci.org/karen-irc/popuko/builds/191223113)

**Pull request merged**
