### PR TITLE
Format the result of auto-merging branch

### PR DESCRIPTION
**Pull request by saneyuki**
This change is [Reviewable](https://reviewable.io/reviews/karen-irc/popuko/203)

### CODE REVIEW

**Comment by saneyuki** [comment]
@popuko r+

**Comment by popuko** [comment]
:pushpin: Commit 929d8f7b79f615931d46ba5ebe5dffc97f07ea52 has been approved by `saneyuki`

**Comment by popuko** [comment]
:hourglass: 929d8f7b79f615931d46ba5ebe5dffc97f07ea52 has been merged into the auto branch ab827a7d8ba8b4e8a4db2ca63cc19208533bd1e8

**Comment by popuko** [comment]
:tada: The result of what tried to merge this pull request is `success`.

* [The Travis CI build passed](https://travis-ci.org/karen-irc/popuko/builds/192268562)

**Pull request merged**
