### PR TITLE
"[demo] Revert  Write fot test"

### PR DESCRIPTION
**Pull request by saneyuki**
Reverts karen-irc/popuko#121

### CODE REVIEW

**Comment by saneyuki** [comment]
@popuko r+

**Comment by popuko** [comment]
:pushpin: Commit e8d3c7b85e6019efe4e95fc0ace9e685c23a698a has been approved by `saneyuki`

**Comment by popuko** [comment]
:hourglass: e8d3c7b85e6019efe4e95fc0ace9e685c23a698a has been merged into the auto branch https://github.com/karen-irc/popuko/commit/2b720fd188174c7dd1a6ed35644765892c80cfb6

**Comment by saneyuki** [comment]
@popuko r+

**Comment by popuko** [comment]
:pushpin: Commit e8d3c7b85e6019efe4e95fc0ace9e685c23a698a has been approved by `saneyuki`

**Comment by popuko** [comment]
:postbox: This pull request is queued. Please await the time.

**Comment by popuko** [comment]
:tada: success: The branch testing to merge this pull request into master has been succeed.

* [The Travis CI build passed](https://travis-ci.org/karen-irc/popuko/builds/188760222)

**Comment by popuko** [comment]
:hourglass: Try to merge e8d3c7b85e6019efe4e95fc0ace9e685c23a698a

**Pull request merged**
