### PR TITLE
Support `r? <reviewer>` command

### PR DESCRIPTION
**Pull request by saneyuki**
Fix https://github.com/karen-irc/popuko/issues/110

### CODE REVIEW

**Comment by saneyuki** [comment]
@nekoya r?

**Comment by nekoya** [comment]
@popuko r+

**Comment by popuko** [comment]
:pushpin: Commit af9db955d790bb8daf2dc3e8b637fd49d603fd4d has been approved by `nekoya`

**Comment by popuko** [comment]
:hourglass: af9db955d790bb8daf2dc3e8b637fd49d603fd4d has been merged into the auto branch https://github.com/karen-irc/popuko/commit/2834cbb728728b03fc928c1c00eb1e8d744eb23f

**Comment by popuko** [comment]
:tada: success: The branch testing to merge this pull request into master has been succeed.

* [The Travis CI build passed](https://travis-ci.org/karen-irc/popuko/builds/188723178)

**Comment by popuko** [comment]
:hourglass: Try to merge af9db955d790bb8daf2dc3e8b637fd49d603fd4d into `master`

**Pull request merged**
