### PR TITLE
Enable to register a repository without recompilation

### PR DESCRIPTION
**Pull request by saneyuki**
As the real usecase, It is tired to recompile the app binary on registering a repository. This is very tired.

By this pull request, we will be able to register a repository with only web hook secret.

### CODE REVIEW

**Comment by nekoya** [comment]
@popuko r+

**Comment by nekoya** [comment]
@popuko r+

**Comment by popuko** [comment]
:pushpin: Commit ead7101158ebc29fe160b711a3ff1b04d5a70b97 has been approved by `nekoya`

**Comment by popuko** [comment]
:hourglass: ead7101158ebc29fe160b711a3ff1b04d5a70b97 has been merged into the auto branch https://github.com/karen-irc/popuko/commit/313cee07c34420b149666cdc97250f9031cf870b

**Comment by popuko** [comment]
:tada: success: The branch testing to merge this pull request into master has been succeed.

* [The Travis CI build passed](https://travis-ci.org/karen-irc/popuko/builds/188821755)

**Comment by popuko** [comment]
:hourglass: Try to merge ead7101158ebc29fe160b711a3ff1b04d5a70b97

**Pull request merged**
