### PR TITLE
Parametalize parser test case

### PR DESCRIPTION
**Pull request by saneyuki**
This change is [Reviewable](https://reviewable.io/reviews/karen-irc/popuko/198)

### CODE REVIEW

**Comment by saneyuki** [comment]
@popuko r+

**Comment by popuko** [comment]
:pushpin: Commit 47db0718fa5dc150b2403b8635ca09862e934180 has been approved by `saneyuki`

**Comment by popuko** [comment]
:hourglass: 47db0718fa5dc150b2403b8635ca09862e934180 has been merged into the auto branch 87a8ade5841838048aed335901d396dd467e6750

**Comment by popuko** [comment]
:tada: The result of what tried to merge this pull request is `success`.

* [The Travis CI build passed](https://travis-ci.org/karen-irc/popuko/builds/191352763)

**Pull request merged**
