### PR TITLE
Change the comment which means the result of auto branch

### PR DESCRIPTION
**Pull request by saneyuki**
This change is [Reviewable](https://reviewable.io/reviews/karen-irc/popuko/166)

### CODE REVIEW

**Comment by saneyuki** [comment]
@popuko r+

**Comment by popuko** [comment]
:pushpin: Commit 32cb7d7562b44eca5a5de6dc3390e7786bde5f84 has been approved by `saneyuki`

**Comment by popuko** [comment]
:hourglass: 32cb7d7562b44eca5a5de6dc3390e7786bde5f84 has been merged into the auto branch 7fab9086616fbd0e55abbdb0bc8ec37507be8636

**Comment by popuko** [comment]
:tada: The branch status which tried to merge this pull request into master is: success

* [The Travis CI build passed](https://travis-ci.org/karen-irc/popuko/builds/189440278)

**Pull request merged**
