### PR TITLE
Implement the REST API to get the information of auto merge queue.

### PR DESCRIPTION
**Pull request by saneyuki**
- Fix https://github.com/karen-irc/popuko/issues/94

This change is [Reviewable](https://reviewable.io/reviews/karen-irc/popuko/223)

### CODE REVIEW

**Comment by nekoya** [comment]
Reviewed 4 of 4 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/karen-irc/popuko/223)*

**Comment by nekoya** [comment]
@popuko r+

**Comment by popuko** [comment]
:pushpin: Commit 201fd7156773146223ab6c662b5f8c6ccefffcb5 has been approved by `nekoya`

**Comment by popuko** [comment]
:hourglass: 201fd7156773146223ab6c662b5f8c6ccefffcb5 has been merged into the auto branch 3464cfa30047d135626c62f7f76029225ac024d7

**Comment by popuko** [comment]
:collision: The result of what tried to merge this pull request is `failure`.

* [The Travis CI build failed](https://travis-ci.org/karen-irc/popuko/builds/196845390)

**Comment by saneyuki** [comment]
@popuko r=nekoya

**Comment by popuko** [comment]
:pushpin: Commit 201fd7156773146223ab6c662b5f8c6ccefffcb5 has been approved by `nekoya`

**Comment by popuko** [comment]
:hourglass: 201fd7156773146223ab6c662b5f8c6ccefffcb5 has been merged into the auto branch 504a060eea29f3d7cf6ebc2400c5281f2707a864

**Comment by popuko** [comment]
:tada: The result of what tried to merge this pull request is `success`.

* [The Travis CI build passed](https://travis-ci.org/karen-irc/popuko/builds/196903455)

**Pull request merged**
