### PR TITLE
Remove the complete tasks from README.

### PR DESCRIPTION
**Pull request by saneyuki**
- We efforts to use emoji for the comment which this bot write.
- This bot "almost" parse intelligently.

### CODE REVIEW

**Comment by saneyuki** [comment]
@nekoya r?

This patch is very small.

**Comment by saneyuki** [comment]
@nekoya r?

**Comment by popuko** [comment]
:umbrella: The latest upstream change (presumably [these](https://github.com/karen-irc/popuko/compare/af4e2b8adb0a...5191c07ce3aa)) made this pull request unmergeable. Please resolve the merge conflicts.

**Comment by saneyuki** [comment]
@nekoya r?

**Comment by nekoya** [comment]
@popuko r+

**Comment by popuko** [comment]
:pushpin: Commit 3f2e813f1a2ab9acf431fce7e4e64d7a575be79d has been approved by `nekoya`

**Comment by popuko** [comment]
:hourglass: 3f2e813f1a2ab9acf431fce7e4e64d7a575be79d has been merged into the auto branch https://github.com/karen-irc/popuko/commit/6ca5469b27c82971ab88bc2bde213557e7015552

**Comment by popuko** [comment]
:tada: success: The branch testing to merge this pull request into master has been succeed.

* [The Travis CI build passed](https://travis-ci.org/karen-irc/popuko/builds/186725302)

**Comment by popuko** [comment]
:hourglass: Try to merge 3f2e813f1a2ab9acf431fce7e4e64d7a575be79d into `master`

**Pull request merged**
