### PR TITLE
Add emoji to the comment which cannot merge operation

### PR DESCRIPTION
**Pull request by saneyuki**
This change is [Reviewable](https://reviewable.io/reviews/karen-irc/popuko/165)

### CODE REVIEW

**Comment by saneyuki** [comment]
@popuko r+

**Comment by popuko** [comment]
:pushpin: Commit 0b1756b5a4897fd68a24d550dc8a5b0951547ea3 has been approved by `saneyuki`

**Comment by popuko** [comment]
:hourglass: 0b1756b5a4897fd68a24d550dc8a5b0951547ea3 has been merged into the auto branch 1ec899a46f8feec8c3e7b7d2103ac1e3af071a00

**Comment by saneyuki** [comment]
@popuko r-

**Comment by popuko** [comment]
:outbox_tray: This has been cancelled from the approved queue by `saneyuki`

**Comment by saneyuki** [comment]
@popuko r+

**Comment by popuko** [comment]
:pushpin: Commit c01971fb221a08df30c9eafea6e50ea26e66bca8 has been approved by `saneyuki`

**Comment by popuko** [comment]
:hourglass: c01971fb221a08df30c9eafea6e50ea26e66bca8 has been merged into the auto branch 3f09ceebaf53c4b0e48586c46265d95450949048

**Comment by popuko** [comment]
:tada: success: The branch testing to merge this pull request into master has been succeed.

* [The Travis CI build passed](https://travis-ci.org/karen-irc/popuko/builds/189436652)

**Pull request merged**
