### PR TITLE
Detect unmergeble only about the pull request which will be merged into master

### PR DESCRIPTION
**Pull request by saneyuki**
This change is [Reviewable](https://reviewable.io/reviews/karen-irc/popuko/192)

### CODE REVIEW

**Comment by nekoya** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/karen-irc/popuko/192)*

**Comment by nekoya** [comment]
@popuko r+

**Comment by popuko** [comment]
:pushpin: Commit 334d2f51714bd9b282123e91404fd58cf2cba3fa has been approved by `nekoya`

**Comment by popuko** [comment]
:hourglass: 334d2f51714bd9b282123e91404fd58cf2cba3fa has been merged into the auto branch ef86ab9141266dce66a848b9efcfc8292e0f5123

**Comment by popuko** [comment]
:tada: The result of what tried to merge this pull request is `success`.

* [The Travis CI build passed](https://travis-ci.org/karen-irc/popuko/builds/192226836)

**Pull request merged**
