### PR TITLE
Categorize json field related to auto merge

### PR DESCRIPTION
**Pull request by saneyuki**
This change is [Reviewable](https://reviewable.io/reviews/karen-irc/popuko/219)

### CODE REVIEW

**Comment by saneyuki** [comment]
@popuko r+

**Comment by popuko** [comment]
:pushpin: Commit 6e03496749873410b9dc7bb02b46359318deb130 has been approved by `saneyuki`

**Comment by popuko** [comment]
:hourglass: 6e03496749873410b9dc7bb02b46359318deb130 has been merged into the auto branch 70ba44248f562477b2f86f69ee5ce84f3bc31948

**Comment by popuko** [comment]
:tada: The result of what tried to merge this pull request is `success`.

* [The Travis CI build passed](https://travis-ci.org/karen-irc/popuko/builds/195228671)

**Pull request merged**
