### PR TITLE
Add more debugging info the path to handle unmergeable

### PR DESCRIPTION
**Pull request by saneyuki**
This change is [Reviewable](https://reviewable.io/reviews/karen-irc/popuko/184)

### CODE REVIEW

**Comment by saneyuki** [comment]
@popuko r+

**Comment by popuko** [comment]
:pushpin: Commit 4c8ad7a7f856abc88363443523e8ad2525063127 has been approved by `saneyuki`

**Comment by popuko** [comment]
:hourglass: 4c8ad7a7f856abc88363443523e8ad2525063127 has been merged into the auto branch a771dd557b25f48378c16d6721810398ee790496

**Comment by popuko** [comment]
:tada: The result of what tried to merge this pull request is `success`.

* [The Travis CI build passed](https://travis-ci.org/karen-irc/popuko/builds/190859081)

**Pull request merged**
