### PR TITLE
Add 'Can I reuse this package as a library?'

### PR DESCRIPTION
**Pull request by saneyuki**
This change is [Reviewable](https://reviewable.io/reviews/karen-irc/popuko/171)

### CODE REVIEW

**Comment by saneyuki** [comment]
@popuko r+

**Comment by popuko** [comment]
:pushpin: Commit e2c77d0586baedafda7f14cd1a4827d40d30c8b9 has been approved by `saneyuki`

**Comment by popuko** [comment]
:hourglass: e2c77d0586baedafda7f14cd1a4827d40d30c8b9 has been merged into the auto branch 218dbaf2ef564634a55d333f2b29a3de6849b072

**Comment by popuko** [comment]
:tada: The branch status which tried to merge this pull request into master is: success

* [The Travis CI build passed](https://travis-ci.org/karen-irc/popuko/builds/189549111)

**Pull request merged**
