### PR TITLE
Add the label to the pull request which fails to merge with upstream branch

### PR DESCRIPTION
**Pull request by saneyuki**

### CODE REVIEW

**Comment by nekoya** [comment]
@popuko r+

**Comment by popuko** [comment]
:pushpin: Commit 28b881d01f7bef898737234a8715b93056116160 has been approved by `nekoya`

**Comment by popuko** [comment]
:postbox: This pull request is queued. Please await the time.

**Comment by popuko** [comment]
:pushpin: Commit 28b881d01f7bef898737234a8715b93056116160 has been approved by `saneyuki`

**Comment by popuko** [comment]
:postbox: This pull request is queued. Please await the time.

**Comment by popuko** [comment]
:hourglass: 28b881d01f7bef898737234a8715b93056116160 has been merged into the auto branch https://github.com/karen-irc/popuko/commit/a4194c156aecba658a33f26c4d822c82422e25c3

**Comment by popuko** [comment]
:tada: success: The branch testing to merge this pull request into master has been succeed.

* [The Travis CI build passed](https://travis-ci.org/karen-irc/popuko/builds/189136937)

**Comment by popuko** [comment]
:hourglass: Try to merge 28b881d01f7bef898737234a8715b93056116160

**Pull request merged**
