### PR TITLE
Update the setup guidance

### PR DESCRIPTION
**Pull request by saneyuki**

### CODE REVIEW

**Comment by saneyuki** [comment]
@popuko r+

**Comment by saneyuki** [comment]
@popuko r+

**Comment by saneyuki** [comment]
@popuko r+

**Comment by saneyuki** [comment]
@popuko r+

**Comment by saneyuki** [comment]
@popuko r+

**Comment by saneyuki** [comment]
@popuko r+

**Comment by popuko** [comment]
:pushpin: Commit 1bbd3bc3b079aa12c617cdd74b0cdadb9764e3f0 has been approved by `saneyuki`

**Comment by popuko** [comment]
:hourglass: 1bbd3bc3b079aa12c617cdd74b0cdadb9764e3f0 has been merged into the auto branch https://github.com/karen-irc/popuko/commit/0ca0e46bd1c3820d0b1b9ae65f92714f3aa5ea67

**Comment by popuko** [comment]
:tada: success: The branch testing to merge this pull request into master has been succeed.

* [The Travis CI build passed](https://travis-ci.org/karen-irc/popuko/builds/185701034)

**Comment by popuko** [comment]
:hourglass: Try to merge 1bbd3bc3b079aa12c617cdd74b0cdadb9764e3f0 into `master`

**Pull request merged**
