### PR TITLE
Add more descriptions to 'How to Contribute'.

### PR DESCRIPTION
**Pull request by saneyuki**
This change is [Reviewable](https://reviewable.io/reviews/karen-irc/popuko/201)

### CODE REVIEW

**Comment by saneyuki** [comment]
@popuko r+

**Comment by popuko** [comment]
:pushpin: Commit db825d9532e2d278edea07fe3b3f8c5103ec9389 has been approved by `saneyuki`

**Comment by popuko** [comment]
:hourglass: db825d9532e2d278edea07fe3b3f8c5103ec9389 has been merged into the auto branch ff5305153332c895d7433bdaf2ea6039fe236fc8

**Comment by popuko** [comment]
:tada: The result of what tried to merge this pull request is `success`.

* [The Travis CI build passed](https://travis-ci.org/karen-irc/popuko/builds/192260274)

**Pull request merged**
