### PR TITLE
Move fns related to creating auto branch to operation/

### PR DESCRIPTION
**Pull request by saneyuki**

### CODE REVIEW

**Comment by saneyuki** [comment]
@popuko r+

**Comment by popuko** [comment]
:pushpin: Commit 936306adea46bd9f7a8396cd18bc53a35331363e has been approved by `saneyuki`

**Comment by popuko** [comment]
:hourglass: 936306adea46bd9f7a8396cd18bc53a35331363e has been merged into the auto branch https://github.com/karen-irc/popuko/commit/50a001a1e5f5068b90abea97b5132ee657654af5

**Comment by popuko** [comment]
:tada: success: The branch testing to merge this pull request into master has been succeed.

* [The Travis CI build passed](https://travis-ci.org/karen-irc/popuko/builds/187303763)

**Comment by popuko** [comment]
:hourglass: Try to merge 936306adea46bd9f7a8396cd18bc53a35331363e into `master`

**Pull request merged**
