### PR TITLE
Update Motivation in README.md

### PR DESCRIPTION
**Pull request by saneyuki**
This change is [Reviewable](https://reviewable.io/reviews/karen-irc/popuko/211)

### CODE REVIEW

**Comment by nekoya** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/karen-irc/popuko/211)*

**Comment by nekoya** [comment]
@popuko r+

**Comment by popuko** [comment]
:pushpin: Commit 36098db4e729ca5c898a82567d1bde432f2fe0d1 has been approved by `nekoya`

**Comment by popuko** [comment]
:hourglass: 36098db4e729ca5c898a82567d1bde432f2fe0d1 has been merged into the auto branch 1aae8673f0b6975d233f7c5a3dee5120d4e15f72

**Comment by popuko** [comment]
:tada: The result of what tried to merge this pull request is `success`.

* [The Travis CI build passed](https://travis-ci.org/karen-irc/popuko/builds/194760154)

**Pull request merged**
