### PR TITLE
Add thinking origin

### PR DESCRIPTION
**Pull request by saneyuki**
This change is [Reviewable](https://reviewable.io/reviews/karen-irc/popuko/213)

### CODE REVIEW

**Comment by nekoya** [comment]
@popuko r+

**Comment by popuko** [comment]
:pushpin: Commit d4af3f8625e9ea6093fba76c4486496f6da8a75f has been approved by `nekoya`

**Comment by popuko** [comment]
:hourglass: d4af3f8625e9ea6093fba76c4486496f6da8a75f has been merged into the auto branch 4a1f1500a42805ff2808e90f5172bb4ea21e6d86

**Comment by popuko** [comment]
:tada: The result of what tried to merge this pull request is `success`.

* [The Travis CI build passed](https://travis-ci.org/karen-irc/popuko/builds/194765937)

**Pull request merged**
