### PR TITLE
Parse user id call more strictly.

### PR DESCRIPTION
**Pull request by saneyuki**
This change is [Reviewable](https://reviewable.io/reviews/karen-irc/popuko/189)

### CODE REVIEW

**Comment by saneyuki** [comment]
@popuko r+

**Comment by popuko** [comment]
:pushpin: Commit 6beddb8920635d04f70da20142527945fa4c293d has been approved by `saneyuki`

**Comment by popuko** [comment]
:hourglass: 6beddb8920635d04f70da20142527945fa4c293d has been merged into the auto branch 80114c366f0c9f7eea2a3f8ab8fc8737eb4393b9

**Comment by popuko** [comment]
:tada: The result of what tried to merge this pull request is `success`.

* [The Travis CI build passed](https://travis-ci.org/karen-irc/popuko/builds/190920943)

**Pull request merged**
