### PR TITLE
[Demo] Test to patrol conflict

### PR DESCRIPTION
**Pull request by saneyuki**
This change is [Reviewable](https://reviewable.io/reviews/karen-irc/popuko/193)

### CODE REVIEW

**Comment by saneyuki** [comment]
@popuko r+

**Comment by popuko** [comment]
:pushpin: Commit 8624958fb953565d4d9feeb7d9c3f26eba2c57f4 has been approved by `saneyuki`

**Comment by popuko** [comment]
:hourglass: 8624958fb953565d4d9feeb7d9c3f26eba2c57f4 has been merged into the auto branch d0805c0793956d1195987281cf3212fb42cb77f1

**Comment by popuko** [comment]
:tada: The result of what tried to merge this pull request is `success`.

* [The Travis CI build passed](https://travis-ci.org/karen-irc/popuko/builds/191260940)

**Pull request merged**
