### PR TITLE
Add the semaphore to restrict the number of Goroutine which checks unmergeables

### PR DESCRIPTION
**Pull request by saneyuki**
To avoid the API limits at a moment, this uses `chan int` which has limited buffer as a semaphore.

---
This change is [Reviewable](https://reviewable.io/reviews/karen-irc/popuko/160)

### CODE REVIEW

**Comment by saneyuki** [comment]
@nekoya r?

**Comment by saneyuki** [comment]
@popuko r+

**Comment by popuko** [comment]
:pushpin: Commit b85547ec10d01ba3e56359803a63bfc4ad43a677 has been approved by `saneyuki`

**Comment by popuko** [comment]
:hourglass: b85547ec10d01ba3e56359803a63bfc4ad43a677 has been merged into the auto branch b34c67d321889767fe83c526904f2eb08e38eed0

**Comment by popuko** [comment]
:tada: success: The branch testing to merge this pull request into master has been succeed.

* [The Travis CI build passed](https://travis-ci.org/karen-irc/popuko/builds/189439113)

**Pull request merged**
