### PR TITLE
Try the next next one if the next item cannot merge into upstream to try before merging.

### PR DESCRIPTION
**Pull request by saneyuki**
This change is [Reviewable](https://reviewable.io/reviews/karen-irc/popuko/155)

### CODE REVIEW

**Comment by saneyuki** [comment]
@popuko r+

**Comment by popuko** [comment]
:pushpin: Commit dad56c4672eb9af0799f14b02956e0a551322bf8 has been approved by `saneyuki`

**Comment by popuko** [comment]
:hourglass: dad56c4672eb9af0799f14b02956e0a551322bf8 has been merged into the auto branch https://github.com/karen-irc/popuko/commit/48e181b353c97d990504f1beab9be0ad326b01fb

**Comment by popuko** [comment]
:tada: success: The branch testing to merge this pull request into master has been succeed.

* [The Travis CI build passed](https://travis-ci.org/karen-irc/popuko/builds/189225788)

**Pull request merged**
