### PR TITLE
Add the features section

### PR DESCRIPTION
**Pull request by saneyuki**
This change is [Reviewable](https://reviewable.io/reviews/karen-irc/popuko/168)

### CODE REVIEW

**Comment by nekoya** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/karen-irc/popuko/168)*

**Comment by nekoya** [comment]
@popuko r+

**Comment by popuko** [comment]
:pushpin: Commit 2c5e1658d084e54d5ea759f1d1454e2608da10fd has been approved by `nekoya`

**Comment by popuko** [comment]
:hourglass: 2c5e1658d084e54d5ea759f1d1454e2608da10fd has been merged into the auto branch 1ea7b4e9aed31d890d4542e6f7a11240bcc45ca0

**Comment by popuko** [comment]
:tada: The branch status which tried to merge this pull request into master is: success

* [The Travis CI build passed](https://travis-ci.org/karen-irc/popuko/builds/189463398)

**Pull request merged**
