### PR TITLE
Stop to queue the item twice.

### PR DESCRIPTION
**Pull request by saneyuki**
This change is [Reviewable](https://reviewable.io/reviews/karen-irc/popuko/177)

### CODE REVIEW

**Comment by saneyuki** [comment]
@popuko r+

**Comment by popuko** [comment]
:pushpin: Commit 71f78f908e9c6523f13cf7ee6de2246e141e9ef9 has been approved by `saneyuki`

**Comment by popuko** [comment]
:hourglass: 71f78f908e9c6523f13cf7ee6de2246e141e9ef9 has been merged into the auto branch 7f54beee16ed5b64561a058267e2bfd5dd2bbdf8

**Comment by popuko** [comment]
:tada: The branch status which tried to merge this pull request into master is: success

* [The Travis CI build passed](https://travis-ci.org/karen-irc/popuko/builds/189580844)

**Pull request merged**
