### PR TITLE
Create epic/

### PR DESCRIPTION
**Pull request by saneyuki**
This change is [Reviewable](https://reviewable.io/reviews/karen-irc/popuko/154)

### CODE REVIEW

**Comment by saneyuki** [comment]
@popuko r+

**Comment by popuko** [comment]
:pushpin: Commit 29e9a89fb0d32fd4f12b484c2aa5deddb4c343e8 has been approved by `saneyuki`

**Comment by popuko** [comment]
:hourglass: 29e9a89fb0d32fd4f12b484c2aa5deddb4c343e8 has been merged into the auto branch https://github.com/karen-irc/popuko/commit/f7ed193e095f59edbde837b99957e9c0f93df239

**Comment by popuko** [comment]
:collision: failure: The branch testing to merge this pull request into master has been troubled.

* [The Travis CI build failed](https://travis-ci.org/karen-irc/popuko/builds/189220237)

**Comment by saneyuki** [comment]
@popuko r+

**Comment by popuko** [comment]
:pushpin: Commit 54c2976b78b96ab9c98984806412ebf73d8a1066 has been approved by `saneyuki`

**Comment by popuko** [comment]
:hourglass: 54c2976b78b96ab9c98984806412ebf73d8a1066 has been merged into the auto branch https://github.com/karen-irc/popuko/commit/192b11177ee9470b893cbab540211dd34e3396ad

**Comment by popuko** [comment]
:tada: success: The branch testing to merge this pull request into master has been succeed.

* [The Travis CI build passed](https://travis-ci.org/karen-irc/popuko/builds/189221538)

**Pull request merged**
