### PR TITLE
Modify the comment to the result of trying

### PR DESCRIPTION
**Pull request by saneyuki**
This change is [Reviewable](https://reviewable.io/reviews/karen-irc/popuko/175)

### CODE REVIEW

**Comment by saneyuki** [comment]
fish_color_command

**Comment by saneyuki** [comment]
@popuko r+

**Comment by popuko** [comment]
:pushpin: Commit 763d3dc40481e4de08c6ec4c327f23150bd06176 has been approved by `saneyuki`

**Comment by popuko** [comment]
:postbox: This pull request is queued. Please await the time.

**Comment by saneyuki** [comment]
@popuko r+

**Comment by popuko** [comment]
:pushpin: Commit 763d3dc40481e4de08c6ec4c327f23150bd06176 has been approved by `saneyuki`

**Comment by popuko** [comment]
:hourglass: 763d3dc40481e4de08c6ec4c327f23150bd06176 has been merged into the auto branch 17ec5f22f776eb48d40f0e4c70674b936abbb6fb

**Comment by popuko** [comment]
:tada: The branch status which tried to merge this pull request into master is: success

* [The Travis CI build passed](https://travis-ci.org/karen-irc/popuko/builds/189579365)

**Pull request merged**
